//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


using System;
using System.Runtime.InteropServices;

namespace Noesis
{

public class BindingExpression : BindingExpressionBase {
  internal new static BindingExpression CreateProxy(IntPtr cPtr, bool cMemoryOwn) {
    return new BindingExpression(cPtr, cMemoryOwn);
  }

  internal BindingExpression(IntPtr cPtr, bool cMemoryOwn) : base(cPtr, cMemoryOwn) {
  }

  internal static HandleRef getCPtr(BindingExpression obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  protected BindingExpression() {
  }

  public override void UpdateTarget() {
    NoesisGUI_PINVOKE.BindingExpression_UpdateTarget(swigCPtr);
  }

  public override void UpdateSource() {
    NoesisGUI_PINVOKE.BindingExpression_UpdateSource(swigCPtr);
  }

  public Binding ParentBinding {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.BindingExpression_ParentBinding_get(swigCPtr);
      return (Binding)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

}

}

