//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


using System;
using System.Runtime.InteropServices;

namespace Noesis
{

public class DockPanel : Panel {
  internal new static DockPanel CreateProxy(IntPtr cPtr, bool cMemoryOwn) {
    return new DockPanel(cPtr, cMemoryOwn);
  }

  internal DockPanel(IntPtr cPtr, bool cMemoryOwn) : base(cPtr, cMemoryOwn) {
  }

  internal static HandleRef getCPtr(DockPanel obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  public DockPanel() {
  }

  protected override IntPtr CreateCPtr(Type type, out bool registerExtend) {
    if (type == typeof(DockPanel)) {
      registerExtend = false;
      return NoesisGUI_PINVOKE.new_DockPanel();
    }
    else {
      return base.CreateExtendCPtr(type, out registerExtend);
    }
  }

  public static Dock GetDock(DependencyObject element) {
    if (element == null) throw new ArgumentNullException("element");
    {
      Dock ret = (Dock)NoesisGUI_PINVOKE.DockPanel_GetDock(DependencyObject.getCPtr(element));
      return ret;
    }
  }

  public static void SetDock(DependencyObject element, Dock dock) {
    if (element == null) throw new ArgumentNullException("element");
    {
      NoesisGUI_PINVOKE.DockPanel_SetDock(DependencyObject.getCPtr(element), (int)dock);
    }
  }

  public static DependencyProperty DockProperty {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.DockPanel_DockProperty_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static DependencyProperty LastChildFillProperty {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.DockPanel_LastChildFillProperty_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public bool LastChildFill {
    set {
      NoesisGUI_PINVOKE.DockPanel_LastChildFill_set(swigCPtr, value);
    } 
    get {
      bool ret = NoesisGUI_PINVOKE.DockPanel_LastChildFill_get(swigCPtr);
      return ret;
    } 
  }

  new internal static IntPtr GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.DockPanel_GetStaticType();
    return ret;
  }

  internal new static IntPtr Extend(string typeName) {
    return NoesisGUI_PINVOKE.Extend_DockPanel(Marshal.StringToHGlobalAnsi(typeName));
  }
}

}

