//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


using System;
using System.Runtime.InteropServices;

namespace Noesis
{

public class DragCompletedEventArgs : RoutedEventArgs {
  private HandleRef swigCPtr;

  internal DragCompletedEventArgs(IntPtr cPtr, bool cMemoryOwn) : base(cPtr, cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(DragCompletedEventArgs obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~DragCompletedEventArgs() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          NoesisGUI_PINVOKE.delete_DragCompletedEventArgs(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  internal static new void InvokeHandler(Delegate handler, IntPtr sender, IntPtr args) {
    DragCompletedEventHandler handler_ = (DragCompletedEventHandler)handler;
    if (handler_ != null) {
      handler_(Extend.GetProxy(sender, false), new DragCompletedEventArgs(args, false));
    }
  }

  public bool Canceled {
    get {
      bool ret = NoesisGUI_PINVOKE.DragCompletedEventArgs_Canceled_get(swigCPtr);
      return ret;
    } 
  }

  public float HorizontalChange {
    get {
      float ret = NoesisGUI_PINVOKE.DragCompletedEventArgs_HorizontalChange_get(swigCPtr);
      return ret;
    } 
  }

  public float VerticalChange {
    get {
      float ret = NoesisGUI_PINVOKE.DragCompletedEventArgs_VerticalChange_get(swigCPtr);
      return ret;
    } 
  }

  public DragCompletedEventArgs(object source, bool canceled, float hChange, float vChange) : this(NoesisGUI_PINVOKE.new_DragCompletedEventArgs(Noesis.Extend.GetInstanceHandle(source), canceled, hChange, vChange), true) {
  }

}

}

