//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


using System;
using System.Runtime.InteropServices;
using System.Windows.Input;

namespace Noesis
{

public class ExecutedRoutedEventArgs : RoutedEventArgs {
  private HandleRef swigCPtr;

  internal ExecutedRoutedEventArgs(IntPtr cPtr, bool cMemoryOwn) : base(cPtr, cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(ExecutedRoutedEventArgs obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~ExecutedRoutedEventArgs() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          NoesisGUI_PINVOKE.delete_ExecutedRoutedEventArgs(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  internal static new void InvokeHandler(Delegate handler, IntPtr sender, IntPtr args) {
    ExecutedRoutedEventHandler handler_ = (ExecutedRoutedEventHandler)handler;
    if (handler_ != null) {
      handler_(Extend.GetProxy(sender, false), new ExecutedRoutedEventArgs(args, false));
    }
  }

  public ICommand Command {
    get {
      return GetCommandHelper() as ICommand;
    }
  }

  public object Parameter {
    get {
      return GetParameterHelper();
    }
  }

  private object GetCommandHelper() {
    IntPtr cPtr = NoesisGUI_PINVOKE.ExecutedRoutedEventArgs_GetCommandHelper(swigCPtr);
    return Noesis.Extend.GetProxy(cPtr, false);
  }

  private object GetParameterHelper() {
    IntPtr cPtr = NoesisGUI_PINVOKE.ExecutedRoutedEventArgs_GetParameterHelper(swigCPtr);
    return Noesis.Extend.GetProxy(cPtr, false);
  }

}

}

