//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


using System;
using System.Runtime.InteropServices;

namespace Noesis
{

public enum HitTestFilterBehavior {
  ContinueSkipSelfAndChildren = 0,
  ContinueSkipChildren = 1,
  ContinueSkipSelf = 2,
  Continue = 3,
  Stop = 4
}

}

