//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


using System;
using System.Runtime.InteropServices;

namespace Noesis
{

public class ImageSource : Animatable {
  internal new static ImageSource CreateProxy(IntPtr cPtr, bool cMemoryOwn) {
    return new ImageSource(cPtr, cMemoryOwn);
  }

  internal ImageSource(IntPtr cPtr, bool cMemoryOwn) : base(cPtr, cMemoryOwn) {
  }

  internal static HandleRef getCPtr(ImageSource obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  protected ImageSource() {
  }

  public float Width {
    get {
      float ret = NoesisGUI_PINVOKE.ImageSource_Width_get(swigCPtr);
      return ret;
    } 
  }

  public float Height {
    get {
      float ret = NoesisGUI_PINVOKE.ImageSource_Height_get(swigCPtr);
      return ret;
    } 
  }

  new internal static IntPtr GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.ImageSource_GetStaticType();
    return ret;
  }

}

}

