//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


using System;
using System.Runtime.InteropServices;

namespace Noesis
{

public class MarkupExtension : BaseComponent {
  internal new static MarkupExtension CreateProxy(IntPtr cPtr, bool cMemoryOwn) {
    return new MarkupExtension(cPtr, cMemoryOwn);
  }

  internal MarkupExtension(IntPtr cPtr, bool cMemoryOwn) : base(cPtr, cMemoryOwn) {
  }

  internal static HandleRef getCPtr(MarkupExtension obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  protected MarkupExtension() {
  }

  new internal static IntPtr GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.MarkupExtension_GetStaticType();
    return ret;
  }

}

}

