//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


using System;
using System.Runtime.InteropServices;

namespace Noesis
{

public class MatrixTransform3D : Transform3D {
  internal new static MatrixTransform3D CreateProxy(IntPtr cPtr, bool cMemoryOwn) {
    return new MatrixTransform3D(cPtr, cMemoryOwn);
  }

  internal MatrixTransform3D(IntPtr cPtr, bool cMemoryOwn) : base(cPtr, cMemoryOwn) {
  }

  internal static HandleRef getCPtr(MatrixTransform3D obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  public MatrixTransform3D() {
  }

  protected override IntPtr CreateCPtr(Type type, out bool registerExtend) {
    registerExtend = false;
    return NoesisGUI_PINVOKE.new_MatrixTransform3D__SWIG_0();
  }

  public MatrixTransform3D(Matrix3D matrix) : this(NoesisGUI_PINVOKE.new_MatrixTransform3D__SWIG_1(ref matrix), true) {
  }

  public static DependencyProperty MatrixProperty {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.MatrixTransform3D_MatrixProperty_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public Matrix3D Matrix {
    set {
      NoesisGUI_PINVOKE.MatrixTransform3D_Matrix_set(swigCPtr, ref value);
    }

    get {
      IntPtr ret = NoesisGUI_PINVOKE.MatrixTransform3D_Matrix_get(swigCPtr);
      if (ret != IntPtr.Zero) {
        return Marshal.PtrToStructure<Matrix3D>(ret);
      }
      else {
        return Matrix3D.Identity;
      }
    }

  }

}

}

