//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


using System;
using System.Runtime.InteropServices;

namespace Noesis
{

public class NoesisGUI_ {
  public static void FreeString(IntPtr str) {
    NoesisGUI_PINVOKE.FreeString(str);
  }

  public static IntPtr Bool_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Bool_GetStaticType();
    return ret;
  }

  public static IntPtr Float_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Float_GetStaticType();
    return ret;
  }

  public static IntPtr Double_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Double_GetStaticType();
    return ret;
  }

  public static IntPtr Int_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Int_GetStaticType();
    return ret;
  }

  public static IntPtr UInt_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.UInt_GetStaticType();
    return ret;
  }

  public static IntPtr Short_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Short_GetStaticType();
    return ret;
  }

  public static IntPtr UShort_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.UShort_GetStaticType();
    return ret;
  }

  public static IntPtr Long_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Long_GetStaticType();
    return ret;
  }

  public static IntPtr ULong_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.ULong_GetStaticType();
    return ret;
  }

  public static IntPtr String_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.String_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_Bool_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_Bool_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_Float_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_Float_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_Double_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_Double_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_Int_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_Int_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_UInt_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_UInt_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_Short_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_Short_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_UShort_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_UShort_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_Long_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_Long_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_ULong_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_ULong_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_String_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_String_GetStaticType();
    return ret;
  }

  public static bool Unbox_Bool(IntPtr val) {
    bool ret = NoesisGUI_PINVOKE.Unbox_Bool(val);
    return ret;
  }

  public static float Unbox_Float(IntPtr val) {
    float ret = NoesisGUI_PINVOKE.Unbox_Float(val);
    return ret;
  }

  public static double Unbox_Double(IntPtr val) {
    double ret = NoesisGUI_PINVOKE.Unbox_Double(val);
    return ret;
  }

  public static int Unbox_Int(IntPtr val) {
    int ret = NoesisGUI_PINVOKE.Unbox_Int(val);
    return ret;
  }

  public static uint Unbox_UInt(IntPtr val) {
    uint ret = NoesisGUI_PINVOKE.Unbox_UInt(val);
    return ret;
  }

  public static short Unbox_Short(IntPtr val) {
    short ret = NoesisGUI_PINVOKE.Unbox_Short(val);
    return ret;
  }

  public static ushort Unbox_UShort(IntPtr val) {
    ushort ret = NoesisGUI_PINVOKE.Unbox_UShort(val);
    return ret;
  }

  public static long Unbox_Long(IntPtr val) {
    long ret = NoesisGUI_PINVOKE.Unbox_Long(val);
    return ret;
  }

  public static ulong Unbox_ULong(IntPtr val) {
    ulong ret = NoesisGUI_PINVOKE.Unbox_ULong(val);
    return ret;
  }

  public static string Unbox_String(IntPtr val) {
    IntPtr strPtr = NoesisGUI_PINVOKE.Unbox_String(val);
    string str = Noesis.Extend.StringFromNativeUtf8(strPtr);
    return str;
  }

  public static IntPtr Box_Bool(bool val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_Bool(val);
    return ret;
  }

  public static IntPtr Box_Float(float val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_Float(val);
    return ret;
  }

  public static IntPtr Box_Double(double val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_Double(val);
    return ret;
  }

  public static IntPtr Box_Int(int val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_Int(val);
    return ret;
  }

  public static IntPtr Box_UInt(uint val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_UInt(val);
    return ret;
  }

  public static IntPtr Box_Short(short val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_Short(val);
    return ret;
  }

  public static IntPtr Box_UShort(ushort val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_UShort(val);
    return ret;
  }

  public static IntPtr Box_Long(long val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_Long(val);
    return ret;
  }

  public static IntPtr Box_ULong(ulong val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_ULong(val);
    return ret;
  }

  public static IntPtr Box_String(string val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_String(val != null ? val : string.Empty);
    return ret;
  }

  public static IntPtr Size_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Size_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_Size_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_Size_GetStaticType();
    return ret;
  }

  public static Size Unbox_Size(IntPtr val) {
    IntPtr ret = NoesisGUI_PINVOKE.Unbox_Size(val);
    if (ret != IntPtr.Zero) {
      return Marshal.PtrToStructure<Size>(ret);
    }
    else {
      return new Size();
    }
  }

  public static IntPtr Box_Size(Size val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_Size(ref val);
    return ret;
  }

  public static IntPtr Point_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Point_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_Point_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_Point_GetStaticType();
    return ret;
  }

  public static Point Unbox_Point(IntPtr val) {
    IntPtr ret = NoesisGUI_PINVOKE.Unbox_Point(val);
    if (ret != IntPtr.Zero) {
      return Marshal.PtrToStructure<Point>(ret);
    }
    else {
      return new Point();
    }
  }

  public static IntPtr Box_Point(Point val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_Point(ref val);
    return ret;
  }

  public static IntPtr Rect_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Rect_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_Rect_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_Rect_GetStaticType();
    return ret;
  }

  public static Rect Unbox_Rect(IntPtr val) {
    IntPtr ret = NoesisGUI_PINVOKE.Unbox_Rect(val);
    if (ret != IntPtr.Zero) {
      return Marshal.PtrToStructure<Rect>(ret);
    }
    else {
      return new Rect();
    }
  }

  public static IntPtr Box_Rect(Rect val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_Rect(ref val);
    return ret;
  }

  public static IntPtr Thickness_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Thickness_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_Thickness_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_Thickness_GetStaticType();
    return ret;
  }

  public static Thickness Unbox_Thickness(IntPtr val) {
    IntPtr ret = NoesisGUI_PINVOKE.Unbox_Thickness(val);
    if (ret != IntPtr.Zero) {
      return Marshal.PtrToStructure<Thickness>(ret);
    }
    else {
      return new Thickness();
    }
  }

  public static IntPtr Box_Thickness(Thickness val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_Thickness(ref val);
    return ret;
  }

  public static IntPtr CornerRadius_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.CornerRadius_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_CornerRadius_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_CornerRadius_GetStaticType();
    return ret;
  }

  public static CornerRadius Unbox_CornerRadius(IntPtr val) {
    IntPtr ret = NoesisGUI_PINVOKE.Unbox_CornerRadius(val);
    if (ret != IntPtr.Zero) {
      return Marshal.PtrToStructure<CornerRadius>(ret);
    }
    else {
      return new CornerRadius();
    }
  }

  public static IntPtr Box_CornerRadius(CornerRadius val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_CornerRadius(ref val);
    return ret;
  }

  public static IntPtr Color_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Color_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_Color_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_Color_GetStaticType();
    return ret;
  }

  public static Color Unbox_Color(IntPtr val) {
    IntPtr ret = NoesisGUI_PINVOKE.Unbox_Color(val);
    if (ret != IntPtr.Zero) {
      return Marshal.PtrToStructure<Color>(ret);
    }
    else {
      return new Color();
    }
  }

  public static IntPtr Box_Color(Color val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_Color(ref val);
    return ret;
  }

  public static IntPtr Vector4_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Vector4_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_Vector4_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_Vector4_GetStaticType();
    return ret;
  }

  public static Vector4 Unbox_Vector4(IntPtr val) {
    IntPtr ret = NoesisGUI_PINVOKE.Unbox_Vector4(val);
    if (ret != IntPtr.Zero) {
      return Marshal.PtrToStructure<Vector4>(ret);
    }
    else {
      return new Vector4();
    }
  }

  public static IntPtr Box_Vector4(Vector4 val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_Vector4(ref val);
    return ret;
  }

  public static IntPtr Matrix4_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Matrix4_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_Matrix4_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_Matrix4_GetStaticType();
    return ret;
  }

  public static Matrix4 Unbox_Matrix4(IntPtr val) {
    IntPtr ret = NoesisGUI_PINVOKE.Unbox_Matrix4(val);
    if (ret != IntPtr.Zero) {
      return Marshal.PtrToStructure<Matrix4>(ret);
    }
    else {
      return new Matrix4();
    }
  }

  public static IntPtr Box_Matrix4(Matrix4 val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_Matrix4(ref val);
    return ret;
  }

  public static IntPtr NullableBool_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.NullableBool_GetStaticType();
    return ret;
  }

  public static IntPtr NullableInt16_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.NullableInt16_GetStaticType();
    return ret;
  }

  public static IntPtr NullableUInt16_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.NullableUInt16_GetStaticType();
    return ret;
  }

  public static IntPtr NullableInt32_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.NullableInt32_GetStaticType();
    return ret;
  }

  public static IntPtr NullableUInt32_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.NullableUInt32_GetStaticType();
    return ret;
  }

  public static IntPtr NullableInt64_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.NullableInt64_GetStaticType();
    return ret;
  }

  public static IntPtr NullableUInt64_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.NullableUInt64_GetStaticType();
    return ret;
  }

  public static IntPtr NullableFloat_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.NullableFloat_GetStaticType();
    return ret;
  }

  public static IntPtr NullableDouble_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.NullableDouble_GetStaticType();
    return ret;
  }

  public static IntPtr NullableColor_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.NullableColor_GetStaticType();
    return ret;
  }

  public static IntPtr NullablePoint_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.NullablePoint_GetStaticType();
    return ret;
  }

  public static IntPtr NullableRect_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.NullableRect_GetStaticType();
    return ret;
  }

  public static IntPtr NullableSize_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.NullableSize_GetStaticType();
    return ret;
  }

  public static IntPtr NullableThickness_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.NullableThickness_GetStaticType();
    return ret;
  }

  public static IntPtr NullableCornerRadius_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.NullableCornerRadius_GetStaticType();
    return ret;
  }

  public static IntPtr NullableTimeSpan_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.NullableTimeSpan_GetStaticType();
    return ret;
  }

  public static IntPtr NullableDuration_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.NullableDuration_GetStaticType();
    return ret;
  }

  public static IntPtr NullableKeyTime_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.NullableKeyTime_GetStaticType();
    return ret;
  }

  public static IntPtr UpdateSourceTrigger_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.UpdateSourceTrigger_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_UpdateSourceTrigger_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_UpdateSourceTrigger_GetStaticType();
    return ret;
  }

  public static UpdateSourceTrigger Unbox_UpdateSourceTrigger(IntPtr val) {
    UpdateSourceTrigger ret = (UpdateSourceTrigger)NoesisGUI_PINVOKE.Unbox_UpdateSourceTrigger(val);
    return ret;
  }

  public static IntPtr Box_UpdateSourceTrigger(UpdateSourceTrigger val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_UpdateSourceTrigger((int)val);
    return ret;
  }

  public static IntPtr AlignmentX_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.AlignmentX_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_AlignmentX_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_AlignmentX_GetStaticType();
    return ret;
  }

  public static AlignmentX Unbox_AlignmentX(IntPtr val) {
    AlignmentX ret = (AlignmentX)NoesisGUI_PINVOKE.Unbox_AlignmentX(val);
    return ret;
  }

  public static IntPtr Box_AlignmentX(AlignmentX val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_AlignmentX((int)val);
    return ret;
  }

  public static IntPtr AlignmentY_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.AlignmentY_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_AlignmentY_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_AlignmentY_GetStaticType();
    return ret;
  }

  public static AlignmentY Unbox_AlignmentY(IntPtr val) {
    AlignmentY ret = (AlignmentY)NoesisGUI_PINVOKE.Unbox_AlignmentY(val);
    return ret;
  }

  public static IntPtr Box_AlignmentY(AlignmentY val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_AlignmentY((int)val);
    return ret;
  }

  public static IntPtr AutoToolTipPlacement_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.AutoToolTipPlacement_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_AutoToolTipPlacement_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_AutoToolTipPlacement_GetStaticType();
    return ret;
  }

  public static AutoToolTipPlacement Unbox_AutoToolTipPlacement(IntPtr val) {
    AutoToolTipPlacement ret = (AutoToolTipPlacement)NoesisGUI_PINVOKE.Unbox_AutoToolTipPlacement(val);
    return ret;
  }

  public static IntPtr Box_AutoToolTipPlacement(AutoToolTipPlacement val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_AutoToolTipPlacement((int)val);
    return ret;
  }

  public static IntPtr BindingMode_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.BindingMode_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_BindingMode_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_BindingMode_GetStaticType();
    return ret;
  }

  public static BindingMode Unbox_BindingMode(IntPtr val) {
    BindingMode ret = (BindingMode)NoesisGUI_PINVOKE.Unbox_BindingMode(val);
    return ret;
  }

  public static IntPtr Box_BindingMode(BindingMode val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_BindingMode((int)val);
    return ret;
  }

  public static IntPtr BitmapScalingMode_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.BitmapScalingMode_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_BitmapScalingMode_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_BitmapScalingMode_GetStaticType();
    return ret;
  }

  public static BitmapScalingMode Unbox_BitmapScalingMode(IntPtr val) {
    BitmapScalingMode ret = (BitmapScalingMode)NoesisGUI_PINVOKE.Unbox_BitmapScalingMode(val);
    return ret;
  }

  public static IntPtr Box_BitmapScalingMode(BitmapScalingMode val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_BitmapScalingMode((int)val);
    return ret;
  }

  public static IntPtr BrushMappingMode_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.BrushMappingMode_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_BrushMappingMode_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_BrushMappingMode_GetStaticType();
    return ret;
  }

  public static BrushMappingMode Unbox_BrushMappingMode(IntPtr val) {
    BrushMappingMode ret = (BrushMappingMode)NoesisGUI_PINVOKE.Unbox_BrushMappingMode(val);
    return ret;
  }

  public static IntPtr Box_BrushMappingMode(BrushMappingMode val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_BrushMappingMode((int)val);
    return ret;
  }

  public static IntPtr CharacterCasing_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.CharacterCasing_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_CharacterCasing_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_CharacterCasing_GetStaticType();
    return ret;
  }

  public static CharacterCasing Unbox_CharacterCasing(IntPtr val) {
    CharacterCasing ret = (CharacterCasing)NoesisGUI_PINVOKE.Unbox_CharacterCasing(val);
    return ret;
  }

  public static IntPtr Box_CharacterCasing(CharacterCasing val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_CharacterCasing((int)val);
    return ret;
  }

  public static IntPtr ClickMode_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.ClickMode_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_ClickMode_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_ClickMode_GetStaticType();
    return ret;
  }

  public static ClickMode Unbox_ClickMode(IntPtr val) {
    ClickMode ret = (ClickMode)NoesisGUI_PINVOKE.Unbox_ClickMode(val);
    return ret;
  }

  public static IntPtr Box_ClickMode(ClickMode val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_ClickMode((int)val);
    return ret;
  }

  public static IntPtr ColorInterpolationMode_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.ColorInterpolationMode_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_ColorInterpolationMode_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_ColorInterpolationMode_GetStaticType();
    return ret;
  }

  public static ColorInterpolationMode Unbox_ColorInterpolationMode(IntPtr val) {
    ColorInterpolationMode ret = (ColorInterpolationMode)NoesisGUI_PINVOKE.Unbox_ColorInterpolationMode(val);
    return ret;
  }

  public static IntPtr Box_ColorInterpolationMode(ColorInterpolationMode val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_ColorInterpolationMode((int)val);
    return ret;
  }

  public static IntPtr Cursor_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Cursor_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_Cursor_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_Cursor_GetStaticType();
    return ret;
  }

  public static Cursor Unbox_Cursor(IntPtr val) {
    Cursor ret = (Cursor)NoesisGUI_PINVOKE.Unbox_Cursor(val);
    return ret;
  }

  public static IntPtr Box_Cursor(Cursor val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_Cursor((int)val);
    return ret;
  }

  public static IntPtr Dock_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Dock_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_Dock_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_Dock_GetStaticType();
    return ret;
  }

  public static Dock Unbox_Dock(IntPtr val) {
    Dock ret = (Dock)NoesisGUI_PINVOKE.Unbox_Dock(val);
    return ret;
  }

  public static IntPtr Box_Dock(Dock val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_Dock((int)val);
    return ret;
  }

  public static IntPtr ExpandDirection_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.ExpandDirection_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_ExpandDirection_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_ExpandDirection_GetStaticType();
    return ret;
  }

  public static ExpandDirection Unbox_ExpandDirection(IntPtr val) {
    ExpandDirection ret = (ExpandDirection)NoesisGUI_PINVOKE.Unbox_ExpandDirection(val);
    return ret;
  }

  public static IntPtr Box_ExpandDirection(ExpandDirection val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_ExpandDirection((int)val);
    return ret;
  }

  public static IntPtr FillRule_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.FillRule_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_FillRule_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_FillRule_GetStaticType();
    return ret;
  }

  public static FillRule Unbox_FillRule(IntPtr val) {
    FillRule ret = (FillRule)NoesisGUI_PINVOKE.Unbox_FillRule(val);
    return ret;
  }

  public static IntPtr Box_FillRule(FillRule val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_FillRule((int)val);
    return ret;
  }

  public static IntPtr FlowDirection_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.FlowDirection_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_FlowDirection_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_FlowDirection_GetStaticType();
    return ret;
  }

  public static FlowDirection Unbox_FlowDirection(IntPtr val) {
    FlowDirection ret = (FlowDirection)NoesisGUI_PINVOKE.Unbox_FlowDirection(val);
    return ret;
  }

  public static IntPtr Box_FlowDirection(FlowDirection val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_FlowDirection((int)val);
    return ret;
  }

  public static IntPtr FontStretch_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.FontStretch_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_FontStretch_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_FontStretch_GetStaticType();
    return ret;
  }

  public static FontStretch Unbox_FontStretch(IntPtr val) {
    FontStretch ret = (FontStretch)NoesisGUI_PINVOKE.Unbox_FontStretch(val);
    return ret;
  }

  public static IntPtr Box_FontStretch(FontStretch val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_FontStretch((int)val);
    return ret;
  }

  public static IntPtr FontStyle_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.FontStyle_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_FontStyle_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_FontStyle_GetStaticType();
    return ret;
  }

  public static FontStyle Unbox_FontStyle(IntPtr val) {
    FontStyle ret = (FontStyle)NoesisGUI_PINVOKE.Unbox_FontStyle(val);
    return ret;
  }

  public static IntPtr Box_FontStyle(FontStyle val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_FontStyle((int)val);
    return ret;
  }

  public static IntPtr FontWeight_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.FontWeight_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_FontWeight_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_FontWeight_GetStaticType();
    return ret;
  }

  public static FontWeight Unbox_FontWeight(IntPtr val) {
    FontWeight ret = (FontWeight)NoesisGUI_PINVOKE.Unbox_FontWeight(val);
    return ret;
  }

  public static IntPtr Box_FontWeight(FontWeight val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_FontWeight((int)val);
    return ret;
  }

  public static IntPtr GeometryCombineMode_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.GeometryCombineMode_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_GeometryCombineMode_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_GeometryCombineMode_GetStaticType();
    return ret;
  }

  public static GeometryCombineMode Unbox_GeometryCombineMode(IntPtr val) {
    GeometryCombineMode ret = (GeometryCombineMode)NoesisGUI_PINVOKE.Unbox_GeometryCombineMode(val);
    return ret;
  }

  public static IntPtr Box_GeometryCombineMode(GeometryCombineMode val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_GeometryCombineMode((int)val);
    return ret;
  }

  public static IntPtr GradientSpreadMethod_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.GradientSpreadMethod_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_GradientSpreadMethod_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_GradientSpreadMethod_GetStaticType();
    return ret;
  }

  public static GradientSpreadMethod Unbox_GradientSpreadMethod(IntPtr val) {
    GradientSpreadMethod ret = (GradientSpreadMethod)NoesisGUI_PINVOKE.Unbox_GradientSpreadMethod(val);
    return ret;
  }

  public static IntPtr Box_GradientSpreadMethod(GradientSpreadMethod val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_GradientSpreadMethod((int)val);
    return ret;
  }

  public static IntPtr HorizontalAlignment_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.HorizontalAlignment_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_HorizontalAlignment_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_HorizontalAlignment_GetStaticType();
    return ret;
  }

  public static HorizontalAlignment Unbox_HorizontalAlignment(IntPtr val) {
    HorizontalAlignment ret = (HorizontalAlignment)NoesisGUI_PINVOKE.Unbox_HorizontalAlignment(val);
    return ret;
  }

  public static IntPtr Box_HorizontalAlignment(HorizontalAlignment val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_HorizontalAlignment((int)val);
    return ret;
  }

  public static IntPtr InputScope_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.InputScope_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_InputScope_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_InputScope_GetStaticType();
    return ret;
  }

  public static InputScope Unbox_InputScope(IntPtr val) {
    InputScope ret = (InputScope)NoesisGUI_PINVOKE.Unbox_InputScope(val);
    return ret;
  }

  public static IntPtr Box_InputScope(InputScope val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_InputScope((int)val);
    return ret;
  }

  public static IntPtr KeyboardNavigationMode_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.KeyboardNavigationMode_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_KeyboardNavigationMode_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_KeyboardNavigationMode_GetStaticType();
    return ret;
  }

  public static KeyboardNavigationMode Unbox_KeyboardNavigationMode(IntPtr val) {
    KeyboardNavigationMode ret = (KeyboardNavigationMode)NoesisGUI_PINVOKE.Unbox_KeyboardNavigationMode(val);
    return ret;
  }

  public static IntPtr Box_KeyboardNavigationMode(KeyboardNavigationMode val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_KeyboardNavigationMode((int)val);
    return ret;
  }

  public static IntPtr LineStackingStrategy_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.LineStackingStrategy_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_LineStackingStrategy_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_LineStackingStrategy_GetStaticType();
    return ret;
  }

  public static LineStackingStrategy Unbox_LineStackingStrategy(IntPtr val) {
    LineStackingStrategy ret = (LineStackingStrategy)NoesisGUI_PINVOKE.Unbox_LineStackingStrategy(val);
    return ret;
  }

  public static IntPtr Box_LineStackingStrategy(LineStackingStrategy val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_LineStackingStrategy((int)val);
    return ret;
  }

  public static IntPtr ListSortDirection_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.ListSortDirection_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_ListSortDirection_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_ListSortDirection_GetStaticType();
    return ret;
  }

  public static ListSortDirection Unbox_ListSortDirection(IntPtr val) {
    ListSortDirection ret = (ListSortDirection)NoesisGUI_PINVOKE.Unbox_ListSortDirection(val);
    return ret;
  }

  public static IntPtr Box_ListSortDirection(ListSortDirection val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_ListSortDirection((int)val);
    return ret;
  }

  public static IntPtr MenuItemRole_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.MenuItemRole_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_MenuItemRole_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_MenuItemRole_GetStaticType();
    return ret;
  }

  public static MenuItemRole Unbox_MenuItemRole(IntPtr val) {
    MenuItemRole ret = (MenuItemRole)NoesisGUI_PINVOKE.Unbox_MenuItemRole(val);
    return ret;
  }

  public static IntPtr Box_MenuItemRole(MenuItemRole val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_MenuItemRole((int)val);
    return ret;
  }

  public static IntPtr Orientation_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Orientation_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_Orientation_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_Orientation_GetStaticType();
    return ret;
  }

  public static Orientation Unbox_Orientation(IntPtr val) {
    Orientation ret = (Orientation)NoesisGUI_PINVOKE.Unbox_Orientation(val);
    return ret;
  }

  public static IntPtr Box_Orientation(Orientation val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_Orientation((int)val);
    return ret;
  }

  public static IntPtr OverflowMode_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.OverflowMode_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_OverflowMode_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_OverflowMode_GetStaticType();
    return ret;
  }

  public static OverflowMode Unbox_OverflowMode(IntPtr val) {
    OverflowMode ret = (OverflowMode)NoesisGUI_PINVOKE.Unbox_OverflowMode(val);
    return ret;
  }

  public static IntPtr Box_OverflowMode(OverflowMode val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_OverflowMode((int)val);
    return ret;
  }

  public static IntPtr PenLineCap_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.PenLineCap_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_PenLineCap_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_PenLineCap_GetStaticType();
    return ret;
  }

  public static PenLineCap Unbox_PenLineCap(IntPtr val) {
    PenLineCap ret = (PenLineCap)NoesisGUI_PINVOKE.Unbox_PenLineCap(val);
    return ret;
  }

  public static IntPtr Box_PenLineCap(PenLineCap val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_PenLineCap((int)val);
    return ret;
  }

  public static IntPtr PenLineJoin_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.PenLineJoin_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_PenLineJoin_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_PenLineJoin_GetStaticType();
    return ret;
  }

  public static PenLineJoin Unbox_PenLineJoin(IntPtr val) {
    PenLineJoin ret = (PenLineJoin)NoesisGUI_PINVOKE.Unbox_PenLineJoin(val);
    return ret;
  }

  public static IntPtr Box_PenLineJoin(PenLineJoin val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_PenLineJoin((int)val);
    return ret;
  }

  public static IntPtr PlacementMode_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.PlacementMode_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_PlacementMode_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_PlacementMode_GetStaticType();
    return ret;
  }

  public static PlacementMode Unbox_PlacementMode(IntPtr val) {
    PlacementMode ret = (PlacementMode)NoesisGUI_PINVOKE.Unbox_PlacementMode(val);
    return ret;
  }

  public static IntPtr Box_PlacementMode(PlacementMode val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_PlacementMode((int)val);
    return ret;
  }

  public static IntPtr PopupAnimation_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.PopupAnimation_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_PopupAnimation_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_PopupAnimation_GetStaticType();
    return ret;
  }

  public static PopupAnimation Unbox_PopupAnimation(IntPtr val) {
    PopupAnimation ret = (PopupAnimation)NoesisGUI_PINVOKE.Unbox_PopupAnimation(val);
    return ret;
  }

  public static IntPtr Box_PopupAnimation(PopupAnimation val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_PopupAnimation((int)val);
    return ret;
  }

  public static IntPtr RelativeSourceMode_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.RelativeSourceMode_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_RelativeSourceMode_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_RelativeSourceMode_GetStaticType();
    return ret;
  }

  public static RelativeSourceMode Unbox_RelativeSourceMode(IntPtr val) {
    RelativeSourceMode ret = (RelativeSourceMode)NoesisGUI_PINVOKE.Unbox_RelativeSourceMode(val);
    return ret;
  }

  public static IntPtr Box_RelativeSourceMode(RelativeSourceMode val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_RelativeSourceMode((int)val);
    return ret;
  }

  public static IntPtr SelectionMode_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.SelectionMode_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_SelectionMode_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_SelectionMode_GetStaticType();
    return ret;
  }

  public static SelectionMode Unbox_SelectionMode(IntPtr val) {
    SelectionMode ret = (SelectionMode)NoesisGUI_PINVOKE.Unbox_SelectionMode(val);
    return ret;
  }

  public static IntPtr Box_SelectionMode(SelectionMode val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_SelectionMode((int)val);
    return ret;
  }

  public static IntPtr ScrollBarVisibility_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.ScrollBarVisibility_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_ScrollBarVisibility_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_ScrollBarVisibility_GetStaticType();
    return ret;
  }

  public static ScrollBarVisibility Unbox_ScrollBarVisibility(IntPtr val) {
    ScrollBarVisibility ret = (ScrollBarVisibility)NoesisGUI_PINVOKE.Unbox_ScrollBarVisibility(val);
    return ret;
  }

  public static IntPtr Box_ScrollBarVisibility(ScrollBarVisibility val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_ScrollBarVisibility((int)val);
    return ret;
  }

  public static IntPtr Stretch_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Stretch_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_Stretch_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_Stretch_GetStaticType();
    return ret;
  }

  public static Stretch Unbox_Stretch(IntPtr val) {
    Stretch ret = (Stretch)NoesisGUI_PINVOKE.Unbox_Stretch(val);
    return ret;
  }

  public static IntPtr Box_Stretch(Stretch val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_Stretch((int)val);
    return ret;
  }

  public static IntPtr StretchDirection_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.StretchDirection_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_StretchDirection_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_StretchDirection_GetStaticType();
    return ret;
  }

  public static StretchDirection Unbox_StretchDirection(IntPtr val) {
    StretchDirection ret = (StretchDirection)NoesisGUI_PINVOKE.Unbox_StretchDirection(val);
    return ret;
  }

  public static IntPtr Box_StretchDirection(StretchDirection val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_StretchDirection((int)val);
    return ret;
  }

  public static IntPtr TextDecorations_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.TextDecorations_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_TextDecorations_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_TextDecorations_GetStaticType();
    return ret;
  }

  public static TextDecorations Unbox_TextDecorations(IntPtr val) {
    TextDecorations ret = (TextDecorations)NoesisGUI_PINVOKE.Unbox_TextDecorations(val);
    return ret;
  }

  public static IntPtr Box_TextDecorations(TextDecorations val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_TextDecorations((int)val);
    return ret;
  }

  public static IntPtr TextAlignment_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.TextAlignment_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_TextAlignment_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_TextAlignment_GetStaticType();
    return ret;
  }

  public static TextAlignment Unbox_TextAlignment(IntPtr val) {
    TextAlignment ret = (TextAlignment)NoesisGUI_PINVOKE.Unbox_TextAlignment(val);
    return ret;
  }

  public static IntPtr Box_TextAlignment(TextAlignment val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_TextAlignment((int)val);
    return ret;
  }

  public static IntPtr TextTrimming_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.TextTrimming_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_TextTrimming_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_TextTrimming_GetStaticType();
    return ret;
  }

  public static TextTrimming Unbox_TextTrimming(IntPtr val) {
    TextTrimming ret = (TextTrimming)NoesisGUI_PINVOKE.Unbox_TextTrimming(val);
    return ret;
  }

  public static IntPtr Box_TextTrimming(TextTrimming val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_TextTrimming((int)val);
    return ret;
  }

  public static IntPtr TextWrapping_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.TextWrapping_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_TextWrapping_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_TextWrapping_GetStaticType();
    return ret;
  }

  public static TextWrapping Unbox_TextWrapping(IntPtr val) {
    TextWrapping ret = (TextWrapping)NoesisGUI_PINVOKE.Unbox_TextWrapping(val);
    return ret;
  }

  public static IntPtr Box_TextWrapping(TextWrapping val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_TextWrapping((int)val);
    return ret;
  }

  public static IntPtr TickBarPlacement_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.TickBarPlacement_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_TickBarPlacement_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_TickBarPlacement_GetStaticType();
    return ret;
  }

  public static TickBarPlacement Unbox_TickBarPlacement(IntPtr val) {
    TickBarPlacement ret = (TickBarPlacement)NoesisGUI_PINVOKE.Unbox_TickBarPlacement(val);
    return ret;
  }

  public static IntPtr Box_TickBarPlacement(TickBarPlacement val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_TickBarPlacement((int)val);
    return ret;
  }

  public static IntPtr TickPlacement_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.TickPlacement_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_TickPlacement_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_TickPlacement_GetStaticType();
    return ret;
  }

  public static TickPlacement Unbox_TickPlacement(IntPtr val) {
    TickPlacement ret = (TickPlacement)NoesisGUI_PINVOKE.Unbox_TickPlacement(val);
    return ret;
  }

  public static IntPtr Box_TickPlacement(TickPlacement val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_TickPlacement((int)val);
    return ret;
  }

  public static IntPtr TileMode_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.TileMode_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_TileMode_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_TileMode_GetStaticType();
    return ret;
  }

  public static TileMode Unbox_TileMode(IntPtr val) {
    TileMode ret = (TileMode)NoesisGUI_PINVOKE.Unbox_TileMode(val);
    return ret;
  }

  public static IntPtr Box_TileMode(TileMode val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_TileMode((int)val);
    return ret;
  }

  public static IntPtr VerticalAlignment_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.VerticalAlignment_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_VerticalAlignment_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_VerticalAlignment_GetStaticType();
    return ret;
  }

  public static VerticalAlignment Unbox_VerticalAlignment(IntPtr val) {
    VerticalAlignment ret = (VerticalAlignment)NoesisGUI_PINVOKE.Unbox_VerticalAlignment(val);
    return ret;
  }

  public static IntPtr Box_VerticalAlignment(VerticalAlignment val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_VerticalAlignment((int)val);
    return ret;
  }

  public static IntPtr Visibility_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Visibility_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_Visibility_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_Visibility_GetStaticType();
    return ret;
  }

  public static Visibility Unbox_Visibility(IntPtr val) {
    Visibility ret = (Visibility)NoesisGUI_PINVOKE.Unbox_Visibility(val);
    return ret;
  }

  public static IntPtr Box_Visibility(Visibility val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_Visibility((int)val);
    return ret;
  }

  public static IntPtr Uri_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Uri_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_Uri_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_Uri_GetStaticType();
    return ret;
  }

  public static Uri Unbox_Uri(IntPtr val) {
    IntPtr uriPtr = NoesisGUI_PINVOKE.Unbox_Uri(val);
    string uri = Noesis.Extend.StringFromNativeUtf8(uriPtr);
    return new Uri(uri, UriKind.Relative);
  }

  public static IntPtr Box_Uri(Uri val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_Uri(val != null ? UriHelper.GetPath(val) : string.Empty);
    return ret;
  }

  public static IntPtr RootVisual_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.RootVisual_GetStaticType();
    return ret;
  }

  public static IntPtr DragDropEffects_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.DragDropEffects_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_DragDropEffects_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_DragDropEffects_GetStaticType();
    return ret;
  }

  public static DragDropEffects Unbox_DragDropEffects(IntPtr val) {
    DragDropEffects ret = (DragDropEffects)NoesisGUI_PINVOKE.Unbox_DragDropEffects(val);
    return ret;
  }

  public static IntPtr Box_DragDropEffects(DragDropEffects val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_DragDropEffects((int)val);
    return ret;
  }

  public static IntPtr DragDropKeyStates_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.DragDropKeyStates_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_DragDropKeyStates_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_DragDropKeyStates_GetStaticType();
    return ret;
  }

  public static DragDropKeyStates Unbox_DragDropKeyStates(IntPtr val) {
    DragDropKeyStates ret = (DragDropKeyStates)NoesisGUI_PINVOKE.Unbox_DragDropKeyStates(val);
    return ret;
  }

  public static IntPtr Box_DragDropKeyStates(DragDropKeyStates val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_DragDropKeyStates((int)val);
    return ret;
  }

  public static IntPtr DragAction_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.DragAction_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_DragAction_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_DragAction_GetStaticType();
    return ret;
  }

  public static DragAction Unbox_DragAction(IntPtr val) {
    DragAction ret = (DragAction)NoesisGUI_PINVOKE.Unbox_DragAction(val);
    return ret;
  }

  public static IntPtr Box_DragAction(DragAction val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_DragAction((int)val);
    return ret;
  }

  public static IntPtr PPAAMode_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.PPAAMode_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_PPAAMode_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_PPAAMode_GetStaticType();
    return ret;
  }

  public static PPAAMode Unbox_PPAAMode(IntPtr val) {
    PPAAMode ret = (PPAAMode)NoesisGUI_PINVOKE.Unbox_PPAAMode(val);
    return ret;
  }

  public static IntPtr Box_PPAAMode(PPAAMode val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_PPAAMode((int)val);
    return ret;
  }

  public static IntPtr GeneratorPosition_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.GeneratorPosition_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_GeneratorPosition_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_GeneratorPosition_GetStaticType();
    return ret;
  }

  public static GeneratorPosition Unbox_GeneratorPosition(IntPtr val) {
    IntPtr ret = NoesisGUI_PINVOKE.Unbox_GeneratorPosition(val);
    if (ret != IntPtr.Zero) {
      return Marshal.PtrToStructure<GeneratorPosition>(ret);
    }
    else {
      return new GeneratorPosition();
    }
  }

  public static IntPtr Box_GeneratorPosition(GeneratorPosition val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_GeneratorPosition(ref val);
    return ret;
  }

  public static IntPtr GridLength_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.GridLength_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_GridLength_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_GridLength_GetStaticType();
    return ret;
  }

  public static GridLength Unbox_GridLength(IntPtr val) {
    IntPtr ret = NoesisGUI_PINVOKE.Unbox_GridLength(val);
    if (ret != IntPtr.Zero) {
      return Marshal.PtrToStructure<GridLength>(ret);
    }
    else {
      return new GridLength();
    }
  }

  public static IntPtr Box_GridLength(GridLength val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_GridLength(ref val);
    return ret;
  }

  public static IntPtr PanningMode_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.PanningMode_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_PanningMode_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_PanningMode_GetStaticType();
    return ret;
  }

  public static PanningMode Unbox_PanningMode(IntPtr val) {
    PanningMode ret = (PanningMode)NoesisGUI_PINVOKE.Unbox_PanningMode(val);
    return ret;
  }

  public static IntPtr Box_PanningMode(PanningMode val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_PanningMode((int)val);
    return ret;
  }

  public static IntPtr VirtualizationCacheLength_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.VirtualizationCacheLength_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_VirtualizationCacheLength_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_VirtualizationCacheLength_GetStaticType();
    return ret;
  }

  public static VirtualizationCacheLength Unbox_VirtualizationCacheLength(IntPtr val) {
    IntPtr ret = NoesisGUI_PINVOKE.Unbox_VirtualizationCacheLength(val);
    if (ret != IntPtr.Zero) {
      return Marshal.PtrToStructure<VirtualizationCacheLength>(ret);
    }
    else {
      return new VirtualizationCacheLength();
    }
  }

  public static IntPtr Box_VirtualizationCacheLength(VirtualizationCacheLength val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_VirtualizationCacheLength(ref val);
    return ret;
  }

  public static IntPtr VirtualizationCacheLengthUnit_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.VirtualizationCacheLengthUnit_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_VirtualizationCacheLengthUnit_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_VirtualizationCacheLengthUnit_GetStaticType();
    return ret;
  }

  public static VirtualizationCacheLengthUnit Unbox_VirtualizationCacheLengthUnit(IntPtr val) {
    VirtualizationCacheLengthUnit ret = (VirtualizationCacheLengthUnit)NoesisGUI_PINVOKE.Unbox_VirtualizationCacheLengthUnit(val);
    return ret;
  }

  public static IntPtr Box_VirtualizationCacheLengthUnit(VirtualizationCacheLengthUnit val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_VirtualizationCacheLengthUnit((int)val);
    return ret;
  }

  public static IntPtr VirtualizationMode_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.VirtualizationMode_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_VirtualizationMode_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_VirtualizationMode_GetStaticType();
    return ret;
  }

  public static VirtualizationMode Unbox_VirtualizationMode(IntPtr val) {
    VirtualizationMode ret = (VirtualizationMode)NoesisGUI_PINVOKE.Unbox_VirtualizationMode(val);
    return ret;
  }

  public static IntPtr Box_VirtualizationMode(VirtualizationMode val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_VirtualizationMode((int)val);
    return ret;
  }

  public static IntPtr ScrollUnit_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.ScrollUnit_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_ScrollUnit_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_ScrollUnit_GetStaticType();
    return ret;
  }

  public static ScrollUnit Unbox_ScrollUnit(IntPtr val) {
    ScrollUnit ret = (ScrollUnit)NoesisGUI_PINVOKE.Unbox_ScrollUnit(val);
    return ret;
  }

  public static IntPtr Box_ScrollUnit(ScrollUnit val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_ScrollUnit((int)val);
    return ret;
  }

  public static IntPtr TextBoxView_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.TextBoxView_GetStaticType();
    return ret;
  }

  public static IntPtr HandoffBehavior_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.HandoffBehavior_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_HandoffBehavior_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_HandoffBehavior_GetStaticType();
    return ret;
  }

  public static HandoffBehavior Unbox_HandoffBehavior(IntPtr val) {
    HandoffBehavior ret = (HandoffBehavior)NoesisGUI_PINVOKE.Unbox_HandoffBehavior(val);
    return ret;
  }

  public static IntPtr Box_HandoffBehavior(HandoffBehavior val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_HandoffBehavior((int)val);
    return ret;
  }

  public static IntPtr TimeSpan_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.TimeSpan_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_TimeSpan_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_TimeSpan_GetStaticType();
    return ret;
  }

  public static TimeSpan Unbox_TimeSpan(IntPtr val) {
    IntPtr ret = NoesisGUI_PINVOKE.Unbox_TimeSpan(val);
    if (ret != IntPtr.Zero) {
      return Marshal.PtrToStructure<TimeSpanStruct>(ret);
    }
    else {
      return new TimeSpan();
    }
  }

  public static IntPtr Box_TimeSpan(TimeSpan val) {
    TimeSpanStruct tempval = val;
    {
      IntPtr ret = NoesisGUI_PINVOKE.Box_TimeSpan(ref tempval);
      return ret;
    }
  }

  public static IntPtr Duration_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Duration_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_Duration_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_Duration_GetStaticType();
    return ret;
  }

  public static Duration Unbox_Duration(IntPtr val) {
    IntPtr ret = NoesisGUI_PINVOKE.Unbox_Duration(val);
    if (ret != IntPtr.Zero) {
      return Marshal.PtrToStructure<Duration>(ret);
    }
    else {
      return new Duration();
    }
  }

  public static IntPtr Box_Duration(Duration val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_Duration(ref val);
    return ret;
  }

  public static IntPtr KeyTime_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.KeyTime_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_KeyTime_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_KeyTime_GetStaticType();
    return ret;
  }

  public static KeyTime Unbox_KeyTime(IntPtr val) {
    IntPtr ret = NoesisGUI_PINVOKE.Unbox_KeyTime(val);
    if (ret != IntPtr.Zero) {
      return Marshal.PtrToStructure<KeyTime>(ret);
    }
    else {
      return new KeyTime();
    }
  }

  public static IntPtr Box_KeyTime(KeyTime val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_KeyTime(ref val);
    return ret;
  }

  public static IntPtr RepeatBehavior_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.RepeatBehavior_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_RepeatBehavior_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_RepeatBehavior_GetStaticType();
    return ret;
  }

  public static RepeatBehavior Unbox_RepeatBehavior(IntPtr val) {
    IntPtr ret = NoesisGUI_PINVOKE.Unbox_RepeatBehavior(val);
    if (ret != IntPtr.Zero) {
      return Marshal.PtrToStructure<RepeatBehavior>(ret);
    }
    else {
      return new RepeatBehavior();
    }
  }

  public static IntPtr Box_RepeatBehavior(RepeatBehavior val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_RepeatBehavior(ref val);
    return ret;
  }

  public static IntPtr ClockState_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.ClockState_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_ClockState_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_ClockState_GetStaticType();
    return ret;
  }

  public static ClockState Unbox_ClockState(IntPtr val) {
    ClockState ret = (ClockState)NoesisGUI_PINVOKE.Unbox_ClockState(val);
    return ret;
  }

  public static IntPtr Box_ClockState(ClockState val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_ClockState((int)val);
    return ret;
  }

  public static IntPtr FillBehavior_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.FillBehavior_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_FillBehavior_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_FillBehavior_GetStaticType();
    return ret;
  }

  public static FillBehavior Unbox_FillBehavior(IntPtr val) {
    FillBehavior ret = (FillBehavior)NoesisGUI_PINVOKE.Unbox_FillBehavior(val);
    return ret;
  }

  public static IntPtr Box_FillBehavior(FillBehavior val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_FillBehavior((int)val);
    return ret;
  }

  public static IntPtr SlipBehavior_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.SlipBehavior_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_SlipBehavior_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_SlipBehavior_GetStaticType();
    return ret;
  }

  public static SlipBehavior Unbox_SlipBehavior(IntPtr val) {
    SlipBehavior ret = (SlipBehavior)NoesisGUI_PINVOKE.Unbox_SlipBehavior(val);
    return ret;
  }

  public static IntPtr Box_SlipBehavior(SlipBehavior val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_SlipBehavior((int)val);
    return ret;
  }

  public static IntPtr EasingMode_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.EasingMode_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_EasingMode_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_EasingMode_GetStaticType();
    return ret;
  }

  public static EasingMode Unbox_EasingMode(IntPtr val) {
    EasingMode ret = (EasingMode)NoesisGUI_PINVOKE.Unbox_EasingMode(val);
    return ret;
  }

  public static IntPtr Box_EasingMode(EasingMode val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_EasingMode((int)val);
    return ret;
  }

  public static IntPtr GridViewColumnHeaderRole_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.GridViewColumnHeaderRole_GetStaticType();
    return ret;
  }

  public static IntPtr Boxed_GridViewColumnHeaderRole_GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Boxed_GridViewColumnHeaderRole_GetStaticType();
    return ret;
  }

  public static GridViewColumnHeaderRole Unbox_GridViewColumnHeaderRole(IntPtr val) {
    GridViewColumnHeaderRole ret = (GridViewColumnHeaderRole)NoesisGUI_PINVOKE.Unbox_GridViewColumnHeaderRole(val);
    return ret;
  }

  public static IntPtr Box_GridViewColumnHeaderRole(GridViewColumnHeaderRole val) {
    IntPtr ret = NoesisGUI_PINVOKE.Box_GridViewColumnHeaderRole((int)val);
    return ret;
  }

}

}

