//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


using System;
using System.Runtime.InteropServices;

namespace Noesis
{

[StructLayoutAttribute(LayoutKind.Sequential, CharSet = CharSet.Ansi)]
internal struct NullableInt32Rect {

  [MarshalAs(UnmanagedType.U1)]
  private bool _hasValue;
  private Int32Rect _value;

  public bool HasValue { get { return this._hasValue; } }

  public Int32Rect Value {
    get {
      if (!HasValue) {
        throw new InvalidOperationException("Nullable does not have a value");
      }
      return this._value;
    }
  }

  public NullableInt32Rect(Int32Rect v) {
    this._hasValue = true;
    this._value = v;
  }

  public static explicit operator Int32Rect(NullableInt32Rect n) {
    if (!n.HasValue) {
      throw new InvalidOperationException("Nullable does not have a value");
    }
    return n.Value;
  }

  public static implicit operator NullableInt32Rect(Int32Rect v) {
    return new NullableInt32Rect(v);
  }

  public static implicit operator Nullable<Int32Rect>(NullableInt32Rect n) {
    return n.HasValue ? new Nullable<Int32Rect>(n.Value) : new Nullable<Int32Rect>();
  }

  public static implicit operator NullableInt32Rect(Nullable<Int32Rect> n) {
    return n.HasValue ? new NullableInt32Rect(n.Value) : new NullableInt32Rect();
  }

  public static bool operator==(NullableInt32Rect n, Int32Rect v) {
    return n.HasValue && n.Value == v;
  }

  public static bool operator!=(NullableInt32Rect n, Int32Rect v) {
    return !(n == v);
  }

  public static bool operator==(Int32Rect v, NullableInt32Rect n) {
    return n == v;
  }
  
  public static bool operator!=(Int32Rect v, NullableInt32Rect n) {
    return n != v;
  }

  public static bool operator==(NullableInt32Rect n0, NullableInt32Rect n1) {
    return n0.HasValue && n1.HasValue ? n0.Value == n1.Value : n0.HasValue == n1.HasValue;
  }

  public static bool operator!=(NullableInt32Rect n0, NullableInt32Rect n1) {
    return !(n0 == n1);
  }

  public override bool Equals(System.Object obj) {
    return obj is NullableInt32Rect && this == (NullableInt32Rect)obj;
  }

  public bool Equals(NullableInt32Rect n) {
    return this == n;
  }

  public override int GetHashCode() {
    return HasValue ? Value.GetHashCode() : 0;
  }

}

}

