//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


using System;
using System.Runtime.InteropServices;

namespace Noesis
{

public class Path : Shape {
  internal new static Path CreateProxy(IntPtr cPtr, bool cMemoryOwn) {
    return new Path(cPtr, cMemoryOwn);
  }

  internal Path(IntPtr cPtr, bool cMemoryOwn) : base(cPtr, cMemoryOwn) {
  }

  internal static HandleRef getCPtr(Path obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  internal protected override Geometry DefiningGeometry {
    get { return Data; }
  }

  public Path() {
  }

  protected override IntPtr CreateCPtr(Type type, out bool registerExtend) {
    registerExtend = false;
    return NoesisGUI_PINVOKE.new_Path();
  }

  public static DependencyProperty DataProperty {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.Path_DataProperty_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public Geometry Data {
    set {
      NoesisGUI_PINVOKE.Path_Data_set(swigCPtr, Geometry.getCPtr(value));
    } 
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.Path_Data_get(swigCPtr);
      return (Geometry)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

}

}

