//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


using System;
using System.Runtime.InteropServices;

namespace Noesis
{

public class RadialGradientBrush : GradientBrush {
  internal new static RadialGradientBrush CreateProxy(IntPtr cPtr, bool cMemoryOwn) {
    return new RadialGradientBrush(cPtr, cMemoryOwn);
  }

  internal RadialGradientBrush(IntPtr cPtr, bool cMemoryOwn) : base(cPtr, cMemoryOwn) {
  }

  internal static HandleRef getCPtr(RadialGradientBrush obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  public RadialGradientBrush() {
  }

  protected override IntPtr CreateCPtr(Type type, out bool registerExtend) {
    registerExtend = false;
    return NoesisGUI_PINVOKE.new_RadialGradientBrush();
  }

  public static DependencyProperty CenterProperty {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.RadialGradientBrush_CenterProperty_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static DependencyProperty GradientOriginProperty {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.RadialGradientBrush_GradientOriginProperty_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static DependencyProperty RadiusXProperty {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.RadialGradientBrush_RadiusXProperty_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static DependencyProperty RadiusYProperty {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.RadialGradientBrush_RadiusYProperty_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public Point Center {
    set {
      NoesisGUI_PINVOKE.RadialGradientBrush_Center_set(swigCPtr, ref value);
    }

    get {
      IntPtr ret = NoesisGUI_PINVOKE.RadialGradientBrush_Center_get(swigCPtr);
      if (ret != IntPtr.Zero) {
        return Marshal.PtrToStructure<Point>(ret);
      }
      else {
        return new Point();
      }
    }

  }

  public Point GradientOrigin {
    set {
      NoesisGUI_PINVOKE.RadialGradientBrush_GradientOrigin_set(swigCPtr, ref value);
    }

    get {
      IntPtr ret = NoesisGUI_PINVOKE.RadialGradientBrush_GradientOrigin_get(swigCPtr);
      if (ret != IntPtr.Zero) {
        return Marshal.PtrToStructure<Point>(ret);
      }
      else {
        return new Point();
      }
    }

  }

  public float RadiusX {
    set {
      NoesisGUI_PINVOKE.RadialGradientBrush_RadiusX_set(swigCPtr, value);
    } 
    get {
      float ret = NoesisGUI_PINVOKE.RadialGradientBrush_RadiusX_get(swigCPtr);
      return ret;
    } 
  }

  public float RadiusY {
    set {
      NoesisGUI_PINVOKE.RadialGradientBrush_RadiusY_set(swigCPtr, value);
    } 
    get {
      float ret = NoesisGUI_PINVOKE.RadialGradientBrush_RadiusY_get(swigCPtr);
      return ret;
    } 
  }

  new internal static IntPtr GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.RadialGradientBrush_GetStaticType();
    return ret;
  }

}

}

