//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


using System;
using System.Runtime.InteropServices;

namespace Noesis
{

public class RectangleGeometry : Geometry {
  internal new static RectangleGeometry CreateProxy(IntPtr cPtr, bool cMemoryOwn) {
    return new RectangleGeometry(cPtr, cMemoryOwn);
  }

  internal RectangleGeometry(IntPtr cPtr, bool cMemoryOwn) : base(cPtr, cMemoryOwn) {
  }

  internal static HandleRef getCPtr(RectangleGeometry obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  public RectangleGeometry() {
  }

  protected override IntPtr CreateCPtr(Type type, out bool registerExtend) {
    registerExtend = false;
    return NoesisGUI_PINVOKE.new_RectangleGeometry__SWIG_0();
  }

  public RectangleGeometry(Rect rect, float rX, float rY) : this(NoesisGUI_PINVOKE.new_RectangleGeometry__SWIG_1(ref rect, rX, rY), true) {
  }

  public RectangleGeometry(Rect rect, float rX) : this(NoesisGUI_PINVOKE.new_RectangleGeometry__SWIG_2(ref rect, rX), true) {
  }

  public RectangleGeometry(Rect rect) : this(NoesisGUI_PINVOKE.new_RectangleGeometry__SWIG_3(ref rect), true) {
  }

  public override bool IsEmpty() {
    bool ret = NoesisGUI_PINVOKE.RectangleGeometry_IsEmpty(swigCPtr);
    return ret;
  }

  public static DependencyProperty RadiusXProperty {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.RectangleGeometry_RadiusXProperty_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static DependencyProperty RadiusYProperty {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.RectangleGeometry_RadiusYProperty_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static DependencyProperty RectProperty {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.RectangleGeometry_RectProperty_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public float RadiusX {
    set {
      NoesisGUI_PINVOKE.RectangleGeometry_RadiusX_set(swigCPtr, value);
    } 
    get {
      float ret = NoesisGUI_PINVOKE.RectangleGeometry_RadiusX_get(swigCPtr);
      return ret;
    } 
  }

  public float RadiusY {
    set {
      NoesisGUI_PINVOKE.RectangleGeometry_RadiusY_set(swigCPtr, value);
    } 
    get {
      float ret = NoesisGUI_PINVOKE.RectangleGeometry_RadiusY_get(swigCPtr);
      return ret;
    } 
  }

  public Rect Rect {
    set {
      NoesisGUI_PINVOKE.RectangleGeometry_Rect_set(swigCPtr, ref value);
    }

    get {
      IntPtr ret = NoesisGUI_PINVOKE.RectangleGeometry_Rect_get(swigCPtr);
      if (ret != IntPtr.Zero) {
        return Marshal.PtrToStructure<Rect>(ret);
      }
      else {
        return new Rect();
      }
    }

  }

  new internal static IntPtr GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.RectangleGeometry_GetStaticType();
    return ret;
  }

}

}

