//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


using System;
using System.Runtime.InteropServices;

namespace Noesis
{

public static class RenderOptions {
  public static DependencyProperty BitmapScalingModeProperty {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.RenderOptions_BitmapScalingModeProperty_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static BitmapScalingMode GetBitmapScalingMode(DependencyObject obj) {
    if (obj == null) throw new ArgumentNullException("obj");
    {
      BitmapScalingMode ret = (BitmapScalingMode)NoesisGUI_PINVOKE.RenderOptions_GetBitmapScalingMode(DependencyObject.getCPtr(obj));
      return ret;
    }
  }

  public static void SetBitmapScalingMode(DependencyObject obj, BitmapScalingMode bitmapScalingMode) {
    if (obj == null) throw new ArgumentNullException("obj");
    {
      NoesisGUI_PINVOKE.RenderOptions_SetBitmapScalingMode(DependencyObject.getCPtr(obj), (int)bitmapScalingMode);
    }
  }

}

}

