//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


using System;
using System.Runtime.InteropServices;

namespace Noesis
{

public class ScrollViewer : ContentControl {
  internal new static ScrollViewer CreateProxy(IntPtr cPtr, bool cMemoryOwn) {
    return new ScrollViewer(cPtr, cMemoryOwn);
  }

  internal ScrollViewer(IntPtr cPtr, bool cMemoryOwn) : base(cPtr, cMemoryOwn) {
  }

  internal static HandleRef getCPtr(ScrollViewer obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  #region Events
  public event ScrollChangedEventHandler ScrollChanged {
    add {
      AddHandler(NoesisGUI_PINVOKE.ScrollViewer_ScrollChangedEvent_get(), value);
    }
    remove {
      RemoveHandler(NoesisGUI_PINVOKE.ScrollViewer_ScrollChangedEvent_get(), value);
    }
  }

  #endregion

  public ScrollViewer() {
  }

  protected override IntPtr CreateCPtr(Type type, out bool registerExtend) {
    if (type == typeof(ScrollViewer)) {
      registerExtend = false;
      return NoesisGUI_PINVOKE.new_ScrollViewer();
    }
    else {
      return base.CreateExtendCPtr(type, out registerExtend);
    }
  }

  public static bool GetCanContentScroll(DependencyObject element) {
    if (element == null) throw new ArgumentNullException("element");
    {
      bool ret = NoesisGUI_PINVOKE.ScrollViewer_GetCanContentScroll(DependencyObject.getCPtr(element));
      return ret;
    }
  }

  public static void SetCanContentScroll(DependencyObject element, bool canScroll) {
    if (element == null) throw new ArgumentNullException("element");
    {
      NoesisGUI_PINVOKE.ScrollViewer_SetCanContentScroll(DependencyObject.getCPtr(element), canScroll);
    }
  }

  public static ScrollBarVisibility GetHorizontalScrollBarVisibility(DependencyObject element) {
    if (element == null) throw new ArgumentNullException("element");
    {
      ScrollBarVisibility ret = (ScrollBarVisibility)NoesisGUI_PINVOKE.ScrollViewer_GetHorizontalScrollBarVisibility(DependencyObject.getCPtr(element));
      return ret;
    }
  }

  public static void SetHorizontalScrollBarVisibility(DependencyObject element, ScrollBarVisibility visibility) {
    if (element == null) throw new ArgumentNullException("element");
    {
      NoesisGUI_PINVOKE.ScrollViewer_SetHorizontalScrollBarVisibility(DependencyObject.getCPtr(element), (int)visibility);
    }
  }

  public static ScrollBarVisibility GetVerticalScrollBarVisibility(DependencyObject element) {
    if (element == null) throw new ArgumentNullException("element");
    {
      ScrollBarVisibility ret = (ScrollBarVisibility)NoesisGUI_PINVOKE.ScrollViewer_GetVerticalScrollBarVisibility(DependencyObject.getCPtr(element));
      return ret;
    }
  }

  public static void SetVerticalScrollBarVisibility(DependencyObject element, ScrollBarVisibility visibility) {
    if (element == null) throw new ArgumentNullException("element");
    {
      NoesisGUI_PINVOKE.ScrollViewer_SetVerticalScrollBarVisibility(DependencyObject.getCPtr(element), (int)visibility);
    }
  }

  public static bool GetIsDeferredScrollingEnabled(DependencyObject element) {
    if (element == null) throw new ArgumentNullException("element");
    {
      bool ret = NoesisGUI_PINVOKE.ScrollViewer_GetIsDeferredScrollingEnabled(DependencyObject.getCPtr(element));
      return ret;
    }
  }

  public static void SetIsDeferredScrollingEnabled(DependencyObject element, bool value) {
    if (element == null) throw new ArgumentNullException("element");
    {
      NoesisGUI_PINVOKE.ScrollViewer_SetIsDeferredScrollingEnabled(DependencyObject.getCPtr(element), value);
    }
  }

  public static PanningMode GetPanningMode(DependencyObject element) {
    if (element == null) throw new ArgumentNullException("element");
    {
      PanningMode ret = (PanningMode)NoesisGUI_PINVOKE.ScrollViewer_GetPanningMode(DependencyObject.getCPtr(element));
      return ret;
    }
  }

  public static void SetPanningMode(DependencyObject element, PanningMode panningMode) {
    if (element == null) throw new ArgumentNullException("element");
    {
      NoesisGUI_PINVOKE.ScrollViewer_SetPanningMode(DependencyObject.getCPtr(element), (int)panningMode);
    }
  }

  public static float GetPanningDeceleration(DependencyObject element) {
    if (element == null) throw new ArgumentNullException("element");
    {
      float ret = NoesisGUI_PINVOKE.ScrollViewer_GetPanningDeceleration(DependencyObject.getCPtr(element));
      return ret;
    }
  }

  public static void SetPanningDeceleration(DependencyObject element, float deceleration) {
    if (element == null) throw new ArgumentNullException("element");
    {
      NoesisGUI_PINVOKE.ScrollViewer_SetPanningDeceleration(DependencyObject.getCPtr(element), deceleration);
    }
  }

  public static float GetPanningRatio(DependencyObject element) {
    if (element == null) throw new ArgumentNullException("element");
    {
      float ret = NoesisGUI_PINVOKE.ScrollViewer_GetPanningRatio(DependencyObject.getCPtr(element));
      return ret;
    }
  }

  public static void SetPanningRatio(DependencyObject element, float panningRatio) {
    if (element == null) throw new ArgumentNullException("element");
    {
      NoesisGUI_PINVOKE.ScrollViewer_SetPanningRatio(DependencyObject.getCPtr(element), panningRatio);
    }
  }

  public void LineLeft() {
    NoesisGUI_PINVOKE.ScrollViewer_LineLeft(swigCPtr);
  }

  public void LineRight() {
    NoesisGUI_PINVOKE.ScrollViewer_LineRight(swigCPtr);
  }

  public void LineUp() {
    NoesisGUI_PINVOKE.ScrollViewer_LineUp(swigCPtr);
  }

  public void LineDown() {
    NoesisGUI_PINVOKE.ScrollViewer_LineDown(swigCPtr);
  }

  public void PageLeft() {
    NoesisGUI_PINVOKE.ScrollViewer_PageLeft(swigCPtr);
  }

  public void PageRight() {
    NoesisGUI_PINVOKE.ScrollViewer_PageRight(swigCPtr);
  }

  public void PageUp() {
    NoesisGUI_PINVOKE.ScrollViewer_PageUp(swigCPtr);
  }

  public void PageDown() {
    NoesisGUI_PINVOKE.ScrollViewer_PageDown(swigCPtr);
  }

  public void ScrollToLeftEnd() {
    NoesisGUI_PINVOKE.ScrollViewer_ScrollToLeftEnd(swigCPtr);
  }

  public void ScrollToRightEnd() {
    NoesisGUI_PINVOKE.ScrollViewer_ScrollToRightEnd(swigCPtr);
  }

  public void ScrollToTop() {
    NoesisGUI_PINVOKE.ScrollViewer_ScrollToTop(swigCPtr);
  }

  public void ScrollToBottom() {
    NoesisGUI_PINVOKE.ScrollViewer_ScrollToBottom(swigCPtr);
  }

  public void ScrollToHome() {
    NoesisGUI_PINVOKE.ScrollViewer_ScrollToHome(swigCPtr);
  }

  public void ScrollToEnd() {
    NoesisGUI_PINVOKE.ScrollViewer_ScrollToEnd(swigCPtr);
  }

  public void ScrollToHorizontalOffset(float offset) {
    NoesisGUI_PINVOKE.ScrollViewer_ScrollToHorizontalOffset(swigCPtr, offset);
  }

  public void ScrollToVerticalOffset(float offset) {
    NoesisGUI_PINVOKE.ScrollViewer_ScrollToVerticalOffset(swigCPtr, offset);
  }

  public void InvalidateScrollInfo() {
    NoesisGUI_PINVOKE.ScrollViewer_InvalidateScrollInfo(swigCPtr);
  }

  public static DependencyProperty CanContentScrollProperty {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.ScrollViewer_CanContentScrollProperty_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static DependencyProperty ComputedHorizontalScrollBarVisibilityProperty {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.ScrollViewer_ComputedHorizontalScrollBarVisibilityProperty_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static DependencyProperty ComputedVerticalScrollBarVisibilityProperty {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.ScrollViewer_ComputedVerticalScrollBarVisibilityProperty_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static DependencyProperty ExtentHeightProperty {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.ScrollViewer_ExtentHeightProperty_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static DependencyProperty ExtentWidthProperty {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.ScrollViewer_ExtentWidthProperty_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static DependencyProperty HorizontalOffsetProperty {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.ScrollViewer_HorizontalOffsetProperty_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static DependencyProperty HorizontalScrollBarVisibilityProperty {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.ScrollViewer_HorizontalScrollBarVisibilityProperty_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static DependencyProperty IsDeferredScrollingEnabledProperty {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.ScrollViewer_IsDeferredScrollingEnabledProperty_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static DependencyProperty ScrollableHeightProperty {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.ScrollViewer_ScrollableHeightProperty_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static DependencyProperty ScrollableWidthProperty {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.ScrollViewer_ScrollableWidthProperty_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static DependencyProperty VerticalOffsetProperty {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.ScrollViewer_VerticalOffsetProperty_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static DependencyProperty VerticalScrollBarVisibilityProperty {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.ScrollViewer_VerticalScrollBarVisibilityProperty_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static DependencyProperty ViewportHeightProperty {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.ScrollViewer_ViewportHeightProperty_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static DependencyProperty ViewportWidthProperty {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.ScrollViewer_ViewportWidthProperty_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static DependencyProperty PanningModeProperty {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.ScrollViewer_PanningModeProperty_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static DependencyProperty PanningDecelerationProperty {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.ScrollViewer_PanningDecelerationProperty_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static DependencyProperty PanningRatioProperty {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.ScrollViewer_PanningRatioProperty_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static RoutedEvent ScrollChangedEvent {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.ScrollViewer_ScrollChangedEvent_get();
      return (RoutedEvent)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public bool CanContentScroll {
    set {
      NoesisGUI_PINVOKE.ScrollViewer_CanContentScroll_set(swigCPtr, value);
    } 
    get {
      bool ret = NoesisGUI_PINVOKE.ScrollViewer_CanContentScroll_get(swigCPtr);
      return ret;
    } 
  }

  public ScrollBarVisibility HorizontalScrollBarVisibility {
    set {
      NoesisGUI_PINVOKE.ScrollViewer_HorizontalScrollBarVisibility_set(swigCPtr, (int)value);
    } 
    get {
      ScrollBarVisibility ret = (ScrollBarVisibility)NoesisGUI_PINVOKE.ScrollViewer_HorizontalScrollBarVisibility_get(swigCPtr);
      return ret;
    } 
  }

  public ScrollBarVisibility VerticalScrollBarVisibility {
    set {
      NoesisGUI_PINVOKE.ScrollViewer_VerticalScrollBarVisibility_set(swigCPtr, (int)value);
    } 
    get {
      ScrollBarVisibility ret = (ScrollBarVisibility)NoesisGUI_PINVOKE.ScrollViewer_VerticalScrollBarVisibility_get(swigCPtr);
      return ret;
    } 
  }

  public bool IsDeferredScrollingEnabled {
    set {
      NoesisGUI_PINVOKE.ScrollViewer_IsDeferredScrollingEnabled_set(swigCPtr, value);
    } 
    get {
      bool ret = NoesisGUI_PINVOKE.ScrollViewer_IsDeferredScrollingEnabled_get(swigCPtr);
      return ret;
    } 
  }

  public PanningMode PanningMode {
    set {
      NoesisGUI_PINVOKE.ScrollViewer_PanningMode_set(swigCPtr, (int)value);
    } 
    get {
      PanningMode ret = (PanningMode)NoesisGUI_PINVOKE.ScrollViewer_PanningMode_get(swigCPtr);
      return ret;
    } 
  }

  public float PanningDeceleration {
    set {
      NoesisGUI_PINVOKE.ScrollViewer_PanningDeceleration_set(swigCPtr, value);
    } 
    get {
      float ret = NoesisGUI_PINVOKE.ScrollViewer_PanningDeceleration_get(swigCPtr);
      return ret;
    } 
  }

  public float PanningRatio {
    set {
      NoesisGUI_PINVOKE.ScrollViewer_PanningRatio_set(swigCPtr, value);
    } 
    get {
      float ret = NoesisGUI_PINVOKE.ScrollViewer_PanningRatio_get(swigCPtr);
      return ret;
    } 
  }

  public Visibility ComputedHorizontalScrollBarVisibility {
    get {
      Visibility ret = (Visibility)NoesisGUI_PINVOKE.ScrollViewer_ComputedHorizontalScrollBarVisibility_get(swigCPtr);
      return ret;
    } 
  }

  public Visibility ComputedVerticalScrollBarVisibility {
    get {
      Visibility ret = (Visibility)NoesisGUI_PINVOKE.ScrollViewer_ComputedVerticalScrollBarVisibility_get(swigCPtr);
      return ret;
    } 
  }

  public float ExtentWidth {
    get {
      float ret = NoesisGUI_PINVOKE.ScrollViewer_ExtentWidth_get(swigCPtr);
      return ret;
    } 
  }

  public float ExtentHeight {
    get {
      float ret = NoesisGUI_PINVOKE.ScrollViewer_ExtentHeight_get(swigCPtr);
      return ret;
    } 
  }

  public float HorizontalOffset {
    get {
      float ret = NoesisGUI_PINVOKE.ScrollViewer_HorizontalOffset_get(swigCPtr);
      return ret;
    } 
  }

  public float VerticalOffset {
    get {
      float ret = NoesisGUI_PINVOKE.ScrollViewer_VerticalOffset_get(swigCPtr);
      return ret;
    } 
  }

  public float ScrollableWidth {
    get {
      float ret = NoesisGUI_PINVOKE.ScrollViewer_ScrollableWidth_get(swigCPtr);
      return ret;
    } 
  }

  public float ScrollableHeight {
    get {
      float ret = NoesisGUI_PINVOKE.ScrollViewer_ScrollableHeight_get(swigCPtr);
      return ret;
    } 
  }

  public float ViewportWidth {
    get {
      float ret = NoesisGUI_PINVOKE.ScrollViewer_ViewportWidth_get(swigCPtr);
      return ret;
    } 
  }

  public float ViewportHeight {
    get {
      float ret = NoesisGUI_PINVOKE.ScrollViewer_ViewportHeight_get(swigCPtr);
      return ret;
    } 
  }

  internal new static IntPtr Extend(string typeName) {
    return NoesisGUI_PINVOKE.Extend_ScrollViewer(Marshal.StringToHGlobalAnsi(typeName));
  }
}

}

