//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


using System;
using System.Runtime.InteropServices;

namespace Noesis
{

public class ToolTipEventArgs : RoutedEventArgs {
  private HandleRef swigCPtr;

  internal ToolTipEventArgs(IntPtr cPtr, bool cMemoryOwn) : base(cPtr, cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(ToolTipEventArgs obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~ToolTipEventArgs() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          NoesisGUI_PINVOKE.delete_ToolTipEventArgs(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  internal static new void InvokeHandler(Delegate handler, IntPtr sender, IntPtr args) {
    ToolTipEventHandler handler_ = (ToolTipEventHandler)handler;
    if (handler_ != null) {
      handler_(Extend.GetProxy(sender, false), new ToolTipEventArgs(args, false));
    }
  }

  public ToolTipEventArgs(object source, RoutedEvent arg1) : this(NoesisGUI_PINVOKE.new_ToolTipEventArgs(Noesis.Extend.GetInstanceHandle(source), RoutedEvent.getCPtr(arg1)), true) {
  }

}

}

