//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


using System;
using System.Runtime.InteropServices;

namespace Noesis
{

public class TriggerBase : DependencyObject {
  internal new static TriggerBase CreateProxy(IntPtr cPtr, bool cMemoryOwn) {
    return new TriggerBase(cPtr, cMemoryOwn);
  }

  internal TriggerBase(IntPtr cPtr, bool cMemoryOwn) : base(cPtr, cMemoryOwn) {
  }

  internal static HandleRef getCPtr(TriggerBase obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  protected TriggerBase() {
  }

  public TriggerActionCollection EnterActions {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.TriggerBase_EnterActions_get(swigCPtr);
      return (TriggerActionCollection)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public TriggerActionCollection ExitActions {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.TriggerBase_ExitActions_get(swigCPtr);
      return (TriggerActionCollection)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  new internal static IntPtr GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.TriggerBase_GetStaticType();
    return ret;
  }

}

}

