//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


using System;
using System.Runtime.InteropServices;

namespace Noesis
{

public struct Typography {

  #region Private members
  private DependencyObject _owner;

  internal Typography(DependencyObject owner) {
    _owner = owner;
  }
  #endregion

  int AnnotationAlternates {
    get { return (int)_owner.GetValue(AnnotationAlternatesProperty); }
    set { _owner.SetValue(AnnotationAlternatesProperty, value); }
  }

  FontCapitals Capitals {
    get { return (FontCapitals)_owner.GetValue(CapitalsProperty); }
    set { _owner.SetValue(CapitalsProperty, value); }
  }

  bool CapitalSpacing {
    get { return (bool)_owner.GetValue(CapitalSpacingProperty); }
    set { _owner.SetValue(CapitalSpacingProperty, value); }
  }

  bool CaseSensitiveForms {
    get { return (bool)_owner.GetValue(CaseSensitiveFormsProperty); }
    set { _owner.SetValue(CaseSensitiveFormsProperty, value); }
  }

  bool ContextualAlternates {
    get { return (bool)_owner.GetValue(ContextualAlternatesProperty); }
    set { _owner.SetValue(ContextualAlternatesProperty, value); }
  }

  bool ContextualLigatures {
    get { return (bool)_owner.GetValue(ContextualLigaturesProperty); }
    set { _owner.SetValue(ContextualLigaturesProperty, value); }
  }

  int ContextualSwashes {
    get { return (int)_owner.GetValue(ContextualSwashesProperty); }
    set { _owner.SetValue(ContextualSwashesProperty, value); }
  }

  bool DiscretionaryLigatures {
    get { return (bool)_owner.GetValue(DiscretionaryLigaturesProperty); }
    set { _owner.SetValue(DiscretionaryLigaturesProperty, value); }
  }

  bool EastAsianExpertForms {
    get { return (bool)_owner.GetValue(EastAsianExpertFormsProperty); }
    set { _owner.SetValue(EastAsianExpertFormsProperty, value); }
  }

  FontEastAsianLanguage EastAsianLanguage {
    get { return (FontEastAsianLanguage)_owner.GetValue(EastAsianLanguageProperty); }
    set { _owner.SetValue(EastAsianLanguageProperty, value); }
  }

  FontEastAsianWidths EastAsianWidths {
    get { return (FontEastAsianWidths)_owner.GetValue(EastAsianWidthsProperty); }
    set { _owner.SetValue(EastAsianWidthsProperty, value); }
  }

  FontFraction Fraction {
    get { return (FontFraction)_owner.GetValue(FractionProperty); }
    set { _owner.SetValue(FractionProperty, value); }
  }

  bool HistoricalForms {
    get { return (bool)_owner.GetValue(HistoricalFormsProperty); }
    set { _owner.SetValue(HistoricalFormsProperty, value); }
  }

  bool HistoricalLigatures {
    get { return (bool)_owner.GetValue(HistoricalLigaturesProperty); }
    set { _owner.SetValue(HistoricalLigaturesProperty, value); }
  }

  bool Kerning {
    get { return (bool)_owner.GetValue(KerningProperty); }
    set { _owner.SetValue(KerningProperty, value); }
  }

  bool MathematicalGreek {
    get { return (bool)_owner.GetValue(MathematicalGreekProperty); }
    set { _owner.SetValue(MathematicalGreekProperty, value); }
  }

  FontNumeralAlignment NumeralAlignment {
    get { return (FontNumeralAlignment)_owner.GetValue(NumeralAlignmentProperty); }
    set { _owner.SetValue(NumeralAlignmentProperty, value); }
  }

  FontNumeralStyle NumeralStyle {
    get { return (FontNumeralStyle)_owner.GetValue(NumeralStyleProperty); }
    set { _owner.SetValue(NumeralStyleProperty, value); }
  }

  bool SlashedZero {
    get { return (bool)_owner.GetValue(SlashedZeroProperty); }
    set { _owner.SetValue(SlashedZeroProperty, value); }
  }

  bool StandardLigatures {
    get { return (bool)_owner.GetValue(StandardLigaturesProperty); }
    set { _owner.SetValue(StandardLigaturesProperty, value); }
  }

  int StandardSwashes {
    get { return (int)_owner.GetValue(StandardSwashesProperty); }
    set { _owner.SetValue(StandardSwashesProperty, value); }
  }

  int StylisticAlternates {
    get { return (int)_owner.GetValue(StylisticAlternatesProperty); }
    set { _owner.SetValue(StylisticAlternatesProperty, value); }
  }

  bool StylisticSet1 {
    get { return (bool)_owner.GetValue(StylisticSet1Property); }
    set { _owner.SetValue(StylisticSet1Property, value); }
  }

  bool StylisticSet2 {
    get { return (bool)_owner.GetValue(StylisticSet2Property); }
    set { _owner.SetValue(StylisticSet2Property, value); }
  }

  bool StylisticSet3 {
    get { return (bool)_owner.GetValue(StylisticSet3Property); }
    set { _owner.SetValue(StylisticSet3Property, value); }
  }

  bool StylisticSet4 {
    get { return (bool)_owner.GetValue(StylisticSet4Property); }
    set { _owner.SetValue(StylisticSet4Property, value); }
  }

  bool StylisticSet5 {
    get { return (bool)_owner.GetValue(StylisticSet5Property); }
    set { _owner.SetValue(StylisticSet5Property, value); }
  }

  bool StylisticSet6 {
    get { return (bool)_owner.GetValue(StylisticSet6Property); }
    set { _owner.SetValue(StylisticSet6Property, value); }
  }

  bool StylisticSet7 {
    get { return (bool)_owner.GetValue(StylisticSet7Property); }
    set { _owner.SetValue(StylisticSet7Property, value); }
  }

  bool StylisticSet8 {
    get { return (bool)_owner.GetValue(StylisticSet8Property); }
    set { _owner.SetValue(StylisticSet8Property, value); }
  }

  bool StylisticSet9 {
    get { return (bool)_owner.GetValue(StylisticSet9Property); }
    set { _owner.SetValue(StylisticSet9Property, value); }
  }

  bool StylisticSet10 {
    get { return (bool)_owner.GetValue(StylisticSet10Property); }
    set { _owner.SetValue(StylisticSet10Property, value); }
  }

  bool StylisticSet11 {
    get { return (bool)_owner.GetValue(StylisticSet11Property); }
    set { _owner.SetValue(StylisticSet11Property, value); }
  }

  bool StylisticSet12 {
    get { return (bool)_owner.GetValue(StylisticSet12Property); }
    set { _owner.SetValue(StylisticSet12Property, value); }
  }

  bool StylisticSet13 {
    get { return (bool)_owner.GetValue(StylisticSet13Property); }
    set { _owner.SetValue(StylisticSet13Property, value); }
  }

  bool StylisticSet14 {
    get { return (bool)_owner.GetValue(StylisticSet14Property); }
    set { _owner.SetValue(StylisticSet14Property, value); }
  }

  bool StylisticSet15 {
    get { return (bool)_owner.GetValue(StylisticSet15Property); }
    set { _owner.SetValue(StylisticSet15Property, value); }
  }

  bool StylisticSet16 {
    get { return (bool)_owner.GetValue(StylisticSet16Property); }
    set { _owner.SetValue(StylisticSet16Property, value); }
  }

  bool StylisticSet17 {
    get { return (bool)_owner.GetValue(StylisticSet17Property); }
    set { _owner.SetValue(StylisticSet17Property, value); }
  }

  bool StylisticSet18 {
    get { return (bool)_owner.GetValue(StylisticSet18Property); }
    set { _owner.SetValue(StylisticSet18Property, value); }
  }

  bool StylisticSet19 {
    get { return (bool)_owner.GetValue(StylisticSet19Property); }
    set { _owner.SetValue(StylisticSet19Property, value); }
  }

  bool StylisticSet20 {
    get { return (bool)_owner.GetValue(StylisticSet20Property); }
    set { _owner.SetValue(StylisticSet20Property, value); }
  }

  FontVariants Variants {
    get { return (FontVariants)_owner.GetValue(VariantsProperty); }
    set { _owner.SetValue(VariantsProperty, value); }
  }

  public static DependencyProperty AnnotationAlternatesProperty {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.Typography_AnnotationAlternatesProperty_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static DependencyProperty CapitalsProperty {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.Typography_CapitalsProperty_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static DependencyProperty CapitalSpacingProperty {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.Typography_CapitalSpacingProperty_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static DependencyProperty CaseSensitiveFormsProperty {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.Typography_CaseSensitiveFormsProperty_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static DependencyProperty ContextualAlternatesProperty {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.Typography_ContextualAlternatesProperty_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static DependencyProperty ContextualLigaturesProperty {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.Typography_ContextualLigaturesProperty_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static DependencyProperty ContextualSwashesProperty {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.Typography_ContextualSwashesProperty_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static DependencyProperty DiscretionaryLigaturesProperty {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.Typography_DiscretionaryLigaturesProperty_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static DependencyProperty EastAsianExpertFormsProperty {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.Typography_EastAsianExpertFormsProperty_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static DependencyProperty EastAsianLanguageProperty {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.Typography_EastAsianLanguageProperty_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static DependencyProperty EastAsianWidthsProperty {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.Typography_EastAsianWidthsProperty_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static DependencyProperty FractionProperty {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.Typography_FractionProperty_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static DependencyProperty HistoricalFormsProperty {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.Typography_HistoricalFormsProperty_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static DependencyProperty HistoricalLigaturesProperty {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.Typography_HistoricalLigaturesProperty_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static DependencyProperty KerningProperty {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.Typography_KerningProperty_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static DependencyProperty MathematicalGreekProperty {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.Typography_MathematicalGreekProperty_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static DependencyProperty NumeralAlignmentProperty {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.Typography_NumeralAlignmentProperty_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static DependencyProperty NumeralStyleProperty {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.Typography_NumeralStyleProperty_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static DependencyProperty SlashedZeroProperty {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.Typography_SlashedZeroProperty_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static DependencyProperty StandardLigaturesProperty {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.Typography_StandardLigaturesProperty_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static DependencyProperty StandardSwashesProperty {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.Typography_StandardSwashesProperty_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static DependencyProperty StylisticAlternatesProperty {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.Typography_StylisticAlternatesProperty_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static DependencyProperty StylisticSet1Property {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.Typography_StylisticSet1Property_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static DependencyProperty StylisticSet2Property {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.Typography_StylisticSet2Property_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static DependencyProperty StylisticSet3Property {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.Typography_StylisticSet3Property_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static DependencyProperty StylisticSet4Property {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.Typography_StylisticSet4Property_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static DependencyProperty StylisticSet5Property {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.Typography_StylisticSet5Property_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static DependencyProperty StylisticSet6Property {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.Typography_StylisticSet6Property_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static DependencyProperty StylisticSet7Property {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.Typography_StylisticSet7Property_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static DependencyProperty StylisticSet8Property {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.Typography_StylisticSet8Property_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static DependencyProperty StylisticSet9Property {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.Typography_StylisticSet9Property_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static DependencyProperty StylisticSet10Property {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.Typography_StylisticSet10Property_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static DependencyProperty StylisticSet11Property {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.Typography_StylisticSet11Property_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static DependencyProperty StylisticSet12Property {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.Typography_StylisticSet12Property_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static DependencyProperty StylisticSet13Property {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.Typography_StylisticSet13Property_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static DependencyProperty StylisticSet14Property {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.Typography_StylisticSet14Property_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static DependencyProperty StylisticSet15Property {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.Typography_StylisticSet15Property_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static DependencyProperty StylisticSet16Property {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.Typography_StylisticSet16Property_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static DependencyProperty StylisticSet17Property {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.Typography_StylisticSet17Property_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static DependencyProperty StylisticSet18Property {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.Typography_StylisticSet18Property_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static DependencyProperty StylisticSet19Property {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.Typography_StylisticSet19Property_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static DependencyProperty StylisticSet20Property {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.Typography_StylisticSet20Property_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  public static DependencyProperty VariantsProperty {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.Typography_VariantsProperty_get();
      return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

}

}

