//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


using System;
using System.Runtime.InteropServices;

namespace Noesis
{

public static class Cursors {
  public static Cursor Black = Cursor.None;
  public static Cursor No = Cursor.No;
  public static Cursor Arrow = Cursor.Arrow;
  public static Cursor AppStarting = Cursor.AppStarting;
  public static Cursor Cross = Cursor.Cross;
  public static Cursor Help = Cursor.Help;
  public static Cursor IBeam = Cursor.IBeam;
  public static Cursor SizeAll = Cursor.SizeAll;
  public static Cursor SizeNESW = Cursor.SizeNESW;
  public static Cursor SizeNS = Cursor.SizeNS;
  public static Cursor SizeNWSE = Cursor.SizeNWSE;
  public static Cursor SizeWE = Cursor.SizeWE;
  public static Cursor UpArrow = Cursor.UpArrow;
  public static Cursor Wait = Cursor.Wait;
  public static Cursor Hand = Cursor.Hand;
  public static Cursor Pen = Cursor.Pen;
  public static Cursor ScrollNS = Cursor.ScrollNS;
  public static Cursor ScrollWE = Cursor.ScrollWE;
  public static Cursor ScrollAll = Cursor.ScrollAll;
  public static Cursor ScrollN = Cursor.ScrollN;
  public static Cursor ScrollS = Cursor.ScrollS;
  public static Cursor ScrollW = Cursor.ScrollW;
  public static Cursor ScrollE = Cursor.ScrollE;
  public static Cursor ScrollNW = Cursor.ScrollNW;
  public static Cursor ScrollNE = Cursor.ScrollNE;
  public static Cursor ScrollSW = Cursor.ScrollSW;
  public static Cursor ScrollSE = Cursor.ScrollSE;
  public static Cursor ArrowCD = Cursor.ArrowCD;

}

}

