//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


using System;
using System.Runtime.InteropServices;

namespace Noesis
{

public enum Cursor {
  None = 0,
  No = 1,
  Arrow = 2,
  AppStarting = 3,
  Cross = 4,
  Help = 5,
  IBeam = 6,
  SizeAll = 7,
  SizeNESW = 8,
  SizeNS = 9,
  SizeNWSE = 10,
  SizeWE = 11,
  UpArrow = 12,
  Wait = 13,
  Hand = 14,
  Pen = 15,
  ScrollNS = 16,
  ScrollWE = 17,
  ScrollAll = 18,
  ScrollN = 19,
  ScrollS = 20,
  ScrollW = 21,
  ScrollE = 22,
  ScrollNW = 23,
  ScrollNE = 24,
  ScrollSW = 25,
  ScrollSE = 26,
  ArrowCD = 27,
  Count
}

}

