//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


using System;
using System.Runtime.InteropServices;

namespace Noesis
{

public class GiveFeedbackEventArgs : RoutedEventArgs {
  private HandleRef swigCPtr;

  internal GiveFeedbackEventArgs(IntPtr cPtr, bool cMemoryOwn) : base(cPtr, cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(GiveFeedbackEventArgs obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~GiveFeedbackEventArgs() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          NoesisGUI_PINVOKE.delete_GiveFeedbackEventArgs(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  internal static new void InvokeHandler(Delegate handler, IntPtr sender, IntPtr args) {
    GiveFeedbackEventHandler handler_ = (GiveFeedbackEventHandler)handler;
    if (handler_ != null) {
      handler_(Extend.GetProxy(sender, false), new GiveFeedbackEventArgs(args, false));
    }
  }

  public uint Effects {
    get {
      uint ret = NoesisGUI_PINVOKE.GiveFeedbackEventArgs_Effects_get(swigCPtr);
      return ret;
    } 
  }

  public bool UseDefaultCursors {
    set {
      NoesisGUI_PINVOKE.GiveFeedbackEventArgs_UseDefaultCursors_set(swigCPtr, value);
    } 
    get {
      bool ret = NoesisGUI_PINVOKE.GiveFeedbackEventArgs_UseDefaultCursors_get(swigCPtr);
      return ret;
    } 
  }

  public GiveFeedbackEventArgs(object source, RoutedEvent arg1, uint effects, bool useDefaultCursors) : this(NoesisGUI_PINVOKE.new_GiveFeedbackEventArgs(Noesis.Extend.GetInstanceHandle(source), RoutedEvent.getCPtr(arg1), effects, useDefaultCursors), true) {
  }

}

}

