//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


using System;
using System.Runtime.InteropServices;

namespace Noesis
{

public enum InputScope {
  Default,
  Url,
  FullFilePath,
  FileName,
  EmailUserName,
  EmailSmtpAddress,
  LogOnName,
  PersonalFullName,
  PersonalNamePrefix,
  PersonalGivenName,
  PersonalMiddleName,
  PersonalSurname,
  PersonalNameSuffix,
  PostalAddress,
  PostalCode,
  AddressStreet,
  AddressStateOrProvince,
  AddressCity,
  AddressCountryName,
  AddressCountryShortName,
  CurrencyAmountAndSymbol,
  CurrencyAmount,
  Date,
  DateMonth,
  DateDay,
  DateYear,
  DateMonthName,
  DateDayName,
  Digits,
  Number,
  OneChar,
  Password,
  TelephoneNumber,
  TelephoneCountryCode,
  TelephoneAreaCode,
  TelephoneLocalNumber,
  Time,
  TimeHour,
  TimeMinorSec,
  NumberFullWidth,
  AlphanumericHalfWidth,
  AlphanumericFullWidth,
  CurrencyChinese,
  Bopomofo,
  Hiragana,
  KatakanaHalfWidth,
  KatakanaFullWidth,
  Hanja,
  PhraseList = -1,
  RegularExpression = -2,
  Srgs = -3,
  Xml = -4
}

}

