//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


using System;
using System.Runtime.InteropServices;

namespace Noesis
{

public static class LogicalTreeHelper {
  public static FrameworkElement GetParent(FrameworkElement element) {
    IntPtr cPtr = NoesisGUI_PINVOKE.LogicalTreeHelper_GetParent(FrameworkElement.getCPtr(element));
    return (FrameworkElement)Noesis.Extend.GetProxy(cPtr, false);
  }

  public static uint GetChildrenCount(FrameworkElement element) {
    uint ret = NoesisGUI_PINVOKE.LogicalTreeHelper_GetChildrenCount(FrameworkElement.getCPtr(element));
    return ret;
  }

  private static IntPtr GetChildHelper(FrameworkElement element, int index) {
    IntPtr ret = NoesisGUI_PINVOKE.LogicalTreeHelper_GetChildHelper(FrameworkElement.getCPtr(element), index);
    return ret;
  }

  private static IntPtr FindLogicalNodeHelper(FrameworkElement element, string name) {
    IntPtr ret = NoesisGUI_PINVOKE.LogicalTreeHelper_FindLogicalNodeHelper(FrameworkElement.getCPtr(element), name != null ? name : string.Empty);
    return ret;
  }

}

}

