//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


using System;
using System.Runtime.InteropServices;

namespace Noesis
{

[StructLayoutAttribute(LayoutKind.Sequential, CharSet = CharSet.Ansi)]
internal struct NullableCornerRadius {

  [MarshalAs(UnmanagedType.U1)]
  private bool _hasValue;
  private CornerRadius _value;

  public bool HasValue { get { return this._hasValue; } }

  public CornerRadius Value {
    get {
      if (!HasValue) {
        throw new InvalidOperationException("Nullable does not have a value");
      }
      return this._value;
    }
  }

  public NullableCornerRadius(CornerRadius v) {
    this._hasValue = true;
    this._value = v;
  }

  public static explicit operator CornerRadius(NullableCornerRadius n) {
    if (!n.HasValue) {
      throw new InvalidOperationException("Nullable does not have a value");
    }
    return n.Value;
  }

  public static implicit operator NullableCornerRadius(CornerRadius v) {
    return new NullableCornerRadius(v);
  }

  public static implicit operator Nullable<CornerRadius>(NullableCornerRadius n) {
    return n.HasValue ? new Nullable<CornerRadius>(n.Value) : new Nullable<CornerRadius>();
  }

  public static implicit operator NullableCornerRadius(Nullable<CornerRadius> n) {
    return n.HasValue ? new NullableCornerRadius(n.Value) : new NullableCornerRadius();
  }

  public static bool operator==(NullableCornerRadius n, CornerRadius v) {
    return n.HasValue && n.Value == v;
  }

  public static bool operator!=(NullableCornerRadius n, CornerRadius v) {
    return !(n == v);
  }

  public static bool operator==(CornerRadius v, NullableCornerRadius n) {
    return n == v;
  }
  
  public static bool operator!=(CornerRadius v, NullableCornerRadius n) {
    return n != v;
  }

  public static bool operator==(NullableCornerRadius n0, NullableCornerRadius n1) {
    return n0.HasValue && n1.HasValue ? n0.Value == n1.Value : n0.HasValue == n1.HasValue;
  }

  public static bool operator!=(NullableCornerRadius n0, NullableCornerRadius n1) {
    return !(n0 == n1);
  }

  public override bool Equals(System.Object obj) {
    return obj is NullableCornerRadius && this == (NullableCornerRadius)obj;
  }

  public bool Equals(NullableCornerRadius n) {
    return this == n;
  }

  public override int GetHashCode() {
    return HasValue ? Value.GetHashCode() : 0;
  }

}

}

