//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


using System;
using System.Runtime.InteropServices;

namespace Noesis
{

[StructLayoutAttribute(LayoutKind.Sequential, CharSet = CharSet.Ansi)]
internal struct NullableUInt16 {

  [MarshalAs(UnmanagedType.U1)]
  private bool _hasValue;
  [MarshalAs(UnmanagedType.U2)]
  private ushort _value;

  public bool HasValue { get { return this._hasValue; } }

  public ushort Value {
    get {
      if (!HasValue) {
        throw new InvalidOperationException("Nullable does not have a value");
      }
      return this._value;
    }
  }

  public NullableUInt16(ushort v) {
    this._hasValue = true;
    this._value = v;
  }

  public static explicit operator ushort(NullableUInt16 n) {
    if (!n.HasValue) {
      throw new InvalidOperationException("Nullable does not have a value");
    }
    return n.Value;
  }

  public static implicit operator NullableUInt16(ushort v) {
    return new NullableUInt16(v);
  }

  public static implicit operator Nullable<ushort>(NullableUInt16 n) {
    return n.HasValue ? new Nullable<ushort>(n.Value) : new Nullable<ushort>();
  }

  public static implicit operator NullableUInt16(Nullable<ushort> n) {
    return n.HasValue ? new NullableUInt16(n.Value) : new NullableUInt16();
  }

  public static bool operator==(NullableUInt16 n, ushort v) {
    return n.HasValue && n.Value == v;
  }

  public static bool operator!=(NullableUInt16 n, ushort v) {
    return !(n == v);
  }

  public static bool operator==(ushort v, NullableUInt16 n) {
    return n == v;
  }
  
  public static bool operator!=(ushort v, NullableUInt16 n) {
    return n != v;
  }

  public static bool operator==(NullableUInt16 n0, NullableUInt16 n1) {
    return n0.HasValue && n1.HasValue ? n0.Value == n1.Value : n0.HasValue == n1.HasValue;
  }

  public static bool operator!=(NullableUInt16 n0, NullableUInt16 n1) {
    return !(n0 == n1);
  }

  public override bool Equals(System.Object obj) {
    return obj is NullableUInt16 && this == (NullableUInt16)obj;
  }

  public bool Equals(NullableUInt16 n) {
    return this == n;
  }

  public override int GetHashCode() {
    return HasValue ? Value.GetHashCode() : 0;
  }

}

}

