//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


using System;
using System.Runtime.InteropServices;

namespace Noesis
{

public class Transform : Animatable {
  internal new static Transform CreateProxy(IntPtr cPtr, bool cMemoryOwn) {
    return new Transform(cPtr, cMemoryOwn);
  }

  internal Transform(IntPtr cPtr, bool cMemoryOwn) : base(cPtr, cMemoryOwn) {
  }

  internal static HandleRef getCPtr(Transform obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  protected Transform() {
  }

  public Matrix Value {
    get {
      Matrix value;
      GetTransformHelper(out value);
      return value;
    }
  }

  public static Transform Identity {
    get {
      IntPtr cPtr = NoesisGUI_PINVOKE.Transform_Identity_get();
      return (Transform)Noesis.Extend.GetProxy(cPtr, false);
    }
  }

  private void GetTransformHelper(out Matrix transform) {
    NoesisGUI_PINVOKE.Transform_GetTransformHelper(swigCPtr, out transform);
  }

  new internal static IntPtr GetStaticType() {
    IntPtr ret = NoesisGUI_PINVOKE.Transform_GetStaticType();
    return ret;
  }

}

}

